// Code generated by protoc-gen-gogo.
// source: github.com/gogo/protobuf/gogoproto/gogo.proto
// DO NOT EDIT!

/*
Package mxnet is a generated protocol buffer package.

It is generated from these files:
	github.com/gogo/protobuf/gogoproto/gogo.proto
	github.com/rai-project/carml/proto/carml.org/inference/inference.proto
	github.com/rai-project/dlframework/mxnet/mxnet.proto

It has these top-level messages:
	ErrorStatus
	ContainerArchicture
	Model
	ModelInformations
	MXNetInferenceRequest
	Feature
	MXNetInferenceResponse
	MXNetModelInformationRequest
	Null
*/
package mxnet

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

var E_GoprotoEnumPrefix = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62001,
	Name:          "gogoproto.goproto_enum_prefix",
	Tag:           "varint,62001,opt,name=goproto_enum_prefix,json=goprotoEnumPrefix",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_GoprotoEnumStringer = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62021,
	Name:          "gogoproto.goproto_enum_stringer",
	Tag:           "varint,62021,opt,name=goproto_enum_stringer,json=goprotoEnumStringer",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_EnumStringer = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62022,
	Name:          "gogoproto.enum_stringer",
	Tag:           "varint,62022,opt,name=enum_stringer,json=enumStringer",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_EnumCustomname = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         62023,
	Name:          "gogoproto.enum_customname",
	Tag:           "bytes,62023,opt,name=enum_customname,json=enumCustomname",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Enumdecl = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62024,
	Name:          "gogoproto.enumdecl",
	Tag:           "varint,62024,opt,name=enumdecl",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_EnumvalueCustomname = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         66001,
	Name:          "gogoproto.enumvalue_customname",
	Tag:           "bytes,66001,opt,name=enumvalue_customname,json=enumvalueCustomname",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_GoprotoGettersAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63001,
	Name:          "gogoproto.goproto_getters_all",
	Tag:           "varint,63001,opt,name=goproto_getters_all,json=goprotoGettersAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_GoprotoEnumPrefixAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63002,
	Name:          "gogoproto.goproto_enum_prefix_all",
	Tag:           "varint,63002,opt,name=goproto_enum_prefix_all,json=goprotoEnumPrefixAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_GoprotoStringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63003,
	Name:          "gogoproto.goproto_stringer_all",
	Tag:           "varint,63003,opt,name=goproto_stringer_all,json=goprotoStringerAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_VerboseEqualAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63004,
	Name:          "gogoproto.verbose_equal_all",
	Tag:           "varint,63004,opt,name=verbose_equal_all,json=verboseEqualAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_FaceAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63005,
	Name:          "gogoproto.face_all",
	Tag:           "varint,63005,opt,name=face_all,json=faceAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_GostringAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63006,
	Name:          "gogoproto.gostring_all",
	Tag:           "varint,63006,opt,name=gostring_all,json=gostringAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_PopulateAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63007,
	Name:          "gogoproto.populate_all",
	Tag:           "varint,63007,opt,name=populate_all,json=populateAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_StringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63008,
	Name:          "gogoproto.stringer_all",
	Tag:           "varint,63008,opt,name=stringer_all,json=stringerAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_OnlyoneAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63009,
	Name:          "gogoproto.onlyone_all",
	Tag:           "varint,63009,opt,name=onlyone_all,json=onlyoneAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_EqualAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63013,
	Name:          "gogoproto.equal_all",
	Tag:           "varint,63013,opt,name=equal_all,json=equalAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_DescriptionAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63014,
	Name:          "gogoproto.description_all",
	Tag:           "varint,63014,opt,name=description_all,json=descriptionAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_TestgenAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63015,
	Name:          "gogoproto.testgen_all",
	Tag:           "varint,63015,opt,name=testgen_all,json=testgenAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_BenchgenAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63016,
	Name:          "gogoproto.benchgen_all",
	Tag:           "varint,63016,opt,name=benchgen_all,json=benchgenAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_MarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63017,
	Name:          "gogoproto.marshaler_all",
	Tag:           "varint,63017,opt,name=marshaler_all,json=marshalerAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_UnmarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63018,
	Name:          "gogoproto.unmarshaler_all",
	Tag:           "varint,63018,opt,name=unmarshaler_all,json=unmarshalerAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_StableMarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63019,
	Name:          "gogoproto.stable_marshaler_all",
	Tag:           "varint,63019,opt,name=stable_marshaler_all,json=stableMarshalerAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_SizerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63020,
	Name:          "gogoproto.sizer_all",
	Tag:           "varint,63020,opt,name=sizer_all,json=sizerAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_GoprotoEnumStringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63021,
	Name:          "gogoproto.goproto_enum_stringer_all",
	Tag:           "varint,63021,opt,name=goproto_enum_stringer_all,json=goprotoEnumStringerAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_EnumStringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63022,
	Name:          "gogoproto.enum_stringer_all",
	Tag:           "varint,63022,opt,name=enum_stringer_all,json=enumStringerAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_UnsafeMarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63023,
	Name:          "gogoproto.unsafe_marshaler_all",
	Tag:           "varint,63023,opt,name=unsafe_marshaler_all,json=unsafeMarshalerAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_UnsafeUnmarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63024,
	Name:          "gogoproto.unsafe_unmarshaler_all",
	Tag:           "varint,63024,opt,name=unsafe_unmarshaler_all,json=unsafeUnmarshalerAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_GoprotoExtensionsMapAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63025,
	Name:          "gogoproto.goproto_extensions_map_all",
	Tag:           "varint,63025,opt,name=goproto_extensions_map_all,json=goprotoExtensionsMapAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_GoprotoUnrecognizedAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63026,
	Name:          "gogoproto.goproto_unrecognized_all",
	Tag:           "varint,63026,opt,name=goproto_unrecognized_all,json=goprotoUnrecognizedAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_GogoprotoImport = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63027,
	Name:          "gogoproto.gogoproto_import",
	Tag:           "varint,63027,opt,name=gogoproto_import,json=gogoprotoImport",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_ProtosizerAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63028,
	Name:          "gogoproto.protosizer_all",
	Tag:           "varint,63028,opt,name=protosizer_all,json=protosizerAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_CompareAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63029,
	Name:          "gogoproto.compare_all",
	Tag:           "varint,63029,opt,name=compare_all,json=compareAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_TypedeclAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63030,
	Name:          "gogoproto.typedecl_all",
	Tag:           "varint,63030,opt,name=typedecl_all,json=typedeclAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_EnumdeclAll = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63031,
	Name:          "gogoproto.enumdecl_all",
	Tag:           "varint,63031,opt,name=enumdecl_all,json=enumdeclAll",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_GoprotoRegistration = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63032,
	Name:          "gogoproto.goproto_registration",
	Tag:           "varint,63032,opt,name=goproto_registration,json=goprotoRegistration",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_GoprotoGetters = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64001,
	Name:          "gogoproto.goproto_getters",
	Tag:           "varint,64001,opt,name=goproto_getters,json=goprotoGetters",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_GoprotoStringer = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64003,
	Name:          "gogoproto.goproto_stringer",
	Tag:           "varint,64003,opt,name=goproto_stringer,json=goprotoStringer",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_VerboseEqual = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64004,
	Name:          "gogoproto.verbose_equal",
	Tag:           "varint,64004,opt,name=verbose_equal,json=verboseEqual",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Face = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64005,
	Name:          "gogoproto.face",
	Tag:           "varint,64005,opt,name=face",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Gostring = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64006,
	Name:          "gogoproto.gostring",
	Tag:           "varint,64006,opt,name=gostring",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Populate = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64007,
	Name:          "gogoproto.populate",
	Tag:           "varint,64007,opt,name=populate",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Stringer = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         67008,
	Name:          "gogoproto.stringer",
	Tag:           "varint,67008,opt,name=stringer",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Onlyone = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64009,
	Name:          "gogoproto.onlyone",
	Tag:           "varint,64009,opt,name=onlyone",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Equal = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64013,
	Name:          "gogoproto.equal",
	Tag:           "varint,64013,opt,name=equal",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Description = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64014,
	Name:          "gogoproto.description",
	Tag:           "varint,64014,opt,name=description",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Testgen = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64015,
	Name:          "gogoproto.testgen",
	Tag:           "varint,64015,opt,name=testgen",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Benchgen = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64016,
	Name:          "gogoproto.benchgen",
	Tag:           "varint,64016,opt,name=benchgen",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Marshaler = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64017,
	Name:          "gogoproto.marshaler",
	Tag:           "varint,64017,opt,name=marshaler",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Unmarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64018,
	Name:          "gogoproto.unmarshaler",
	Tag:           "varint,64018,opt,name=unmarshaler",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_StableMarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64019,
	Name:          "gogoproto.stable_marshaler",
	Tag:           "varint,64019,opt,name=stable_marshaler,json=stableMarshaler",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Sizer = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64020,
	Name:          "gogoproto.sizer",
	Tag:           "varint,64020,opt,name=sizer",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_UnsafeMarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64023,
	Name:          "gogoproto.unsafe_marshaler",
	Tag:           "varint,64023,opt,name=unsafe_marshaler,json=unsafeMarshaler",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_UnsafeUnmarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64024,
	Name:          "gogoproto.unsafe_unmarshaler",
	Tag:           "varint,64024,opt,name=unsafe_unmarshaler,json=unsafeUnmarshaler",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_GoprotoExtensionsMap = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64025,
	Name:          "gogoproto.goproto_extensions_map",
	Tag:           "varint,64025,opt,name=goproto_extensions_map,json=goprotoExtensionsMap",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_GoprotoUnrecognized = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64026,
	Name:          "gogoproto.goproto_unrecognized",
	Tag:           "varint,64026,opt,name=goproto_unrecognized,json=goprotoUnrecognized",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Protosizer = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64028,
	Name:          "gogoproto.protosizer",
	Tag:           "varint,64028,opt,name=protosizer",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Compare = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64029,
	Name:          "gogoproto.compare",
	Tag:           "varint,64029,opt,name=compare",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Typedecl = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64030,
	Name:          "gogoproto.typedecl",
	Tag:           "varint,64030,opt,name=typedecl",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Nullable = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65001,
	Name:          "gogoproto.nullable",
	Tag:           "varint,65001,opt,name=nullable",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Embed = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65002,
	Name:          "gogoproto.embed",
	Tag:           "varint,65002,opt,name=embed",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Customtype = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65003,
	Name:          "gogoproto.customtype",
	Tag:           "bytes,65003,opt,name=customtype",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Customname = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65004,
	Name:          "gogoproto.customname",
	Tag:           "bytes,65004,opt,name=customname",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Jsontag = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65005,
	Name:          "gogoproto.jsontag",
	Tag:           "bytes,65005,opt,name=jsontag",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Moretags = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65006,
	Name:          "gogoproto.moretags",
	Tag:           "bytes,65006,opt,name=moretags",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Casttype = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65007,
	Name:          "gogoproto.casttype",
	Tag:           "bytes,65007,opt,name=casttype",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Castkey = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65008,
	Name:          "gogoproto.castkey",
	Tag:           "bytes,65008,opt,name=castkey",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Castvalue = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65009,
	Name:          "gogoproto.castvalue",
	Tag:           "bytes,65009,opt,name=castvalue",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Stdtime = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65010,
	Name:          "gogoproto.stdtime",
	Tag:           "varint,65010,opt,name=stdtime",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

var E_Stdduration = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65011,
	Name:          "gogoproto.stdduration",
	Tag:           "varint,65011,opt,name=stdduration",
	Filename:      "github.com/gogo/protobuf/gogoproto/gogo.proto",
}

func init() {
	proto.RegisterExtension(E_GoprotoEnumPrefix)
	proto.RegisterExtension(E_GoprotoEnumStringer)
	proto.RegisterExtension(E_EnumStringer)
	proto.RegisterExtension(E_EnumCustomname)
	proto.RegisterExtension(E_Enumdecl)
	proto.RegisterExtension(E_EnumvalueCustomname)
	proto.RegisterExtension(E_GoprotoGettersAll)
	proto.RegisterExtension(E_GoprotoEnumPrefixAll)
	proto.RegisterExtension(E_GoprotoStringerAll)
	proto.RegisterExtension(E_VerboseEqualAll)
	proto.RegisterExtension(E_FaceAll)
	proto.RegisterExtension(E_GostringAll)
	proto.RegisterExtension(E_PopulateAll)
	proto.RegisterExtension(E_StringerAll)
	proto.RegisterExtension(E_OnlyoneAll)
	proto.RegisterExtension(E_EqualAll)
	proto.RegisterExtension(E_DescriptionAll)
	proto.RegisterExtension(E_TestgenAll)
	proto.RegisterExtension(E_BenchgenAll)
	proto.RegisterExtension(E_MarshalerAll)
	proto.RegisterExtension(E_UnmarshalerAll)
	proto.RegisterExtension(E_StableMarshalerAll)
	proto.RegisterExtension(E_SizerAll)
	proto.RegisterExtension(E_GoprotoEnumStringerAll)
	proto.RegisterExtension(E_EnumStringerAll)
	proto.RegisterExtension(E_UnsafeMarshalerAll)
	proto.RegisterExtension(E_UnsafeUnmarshalerAll)
	proto.RegisterExtension(E_GoprotoExtensionsMapAll)
	proto.RegisterExtension(E_GoprotoUnrecognizedAll)
	proto.RegisterExtension(E_GogoprotoImport)
	proto.RegisterExtension(E_ProtosizerAll)
	proto.RegisterExtension(E_CompareAll)
	proto.RegisterExtension(E_TypedeclAll)
	proto.RegisterExtension(E_EnumdeclAll)
	proto.RegisterExtension(E_GoprotoRegistration)
	proto.RegisterExtension(E_GoprotoGetters)
	proto.RegisterExtension(E_GoprotoStringer)
	proto.RegisterExtension(E_VerboseEqual)
	proto.RegisterExtension(E_Face)
	proto.RegisterExtension(E_Gostring)
	proto.RegisterExtension(E_Populate)
	proto.RegisterExtension(E_Stringer)
	proto.RegisterExtension(E_Onlyone)
	proto.RegisterExtension(E_Equal)
	proto.RegisterExtension(E_Description)
	proto.RegisterExtension(E_Testgen)
	proto.RegisterExtension(E_Benchgen)
	proto.RegisterExtension(E_Marshaler)
	proto.RegisterExtension(E_Unmarshaler)
	proto.RegisterExtension(E_StableMarshaler)
	proto.RegisterExtension(E_Sizer)
	proto.RegisterExtension(E_UnsafeMarshaler)
	proto.RegisterExtension(E_UnsafeUnmarshaler)
	proto.RegisterExtension(E_GoprotoExtensionsMap)
	proto.RegisterExtension(E_GoprotoUnrecognized)
	proto.RegisterExtension(E_Protosizer)
	proto.RegisterExtension(E_Compare)
	proto.RegisterExtension(E_Typedecl)
	proto.RegisterExtension(E_Nullable)
	proto.RegisterExtension(E_Embed)
	proto.RegisterExtension(E_Customtype)
	proto.RegisterExtension(E_Customname)
	proto.RegisterExtension(E_Jsontag)
	proto.RegisterExtension(E_Moretags)
	proto.RegisterExtension(E_Casttype)
	proto.RegisterExtension(E_Castkey)
	proto.RegisterExtension(E_Castvalue)
	proto.RegisterExtension(E_Stdtime)
	proto.RegisterExtension(E_Stdduration)
}

func init() { proto.RegisterFile("github.com/gogo/protobuf/gogoproto/gogo.proto", fileDescriptorGogo) }

var fileDescriptorGogo = []byte{
	// 1268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x98, 0x4d, 0x6c, 0xdc, 0x44,
	0x14, 0x80, 0xb3, 0x22, 0x55, 0xb2, 0x2f, 0x7f, 0x64, 0x13, 0x42, 0xa9, 0x60, 0x29, 0x37, 0x2e,
	0xa4, 0xa7, 0x0a, 0x75, 0xa2, 0x2a, 0x4a, 0xa3, 0x34, 0x6a, 0x45, 0x20, 0x84, 0xa6, 0x80, 0x38,
	0xac, 0xbc, 0xbb, 0x13, 0xc7, 0x60, 0x7b, 0x8c, 0x3d, 0xae, 0x9a, 0x9e, 0x40, 0xe5, 0x47, 0x08,
	0x01, 0xe5, 0x47, 0x82, 0x96, 0xb6, 0xc0, 0x01, 0x28, 0xff, 0x94, 0xff, 0x23, 0x17, 0xa0, 0xc7,
	0x72, 0xe3, 0x48, 0x16, 0x0e, 0xfc, 0x04, 0x08, 0x90, 0x5b, 0x2e, 0xd5, 0x78, 0xdf, 0xf3, 0xda,
	0x9b, 0x95, 0x66, 0xf6, 0xe6, 0xdd, 0xcc, 0xf7, 0xed, 0xf3, 0x7b, 0x9e, 0xf7, 0xc6, 0x81, 0x3b,
	0x6c, 0x47, 0xae, 0xc6, 0xd5, 0xc9, 0x9a, 0xf0, 0xf6, 0xd9, 0xc2, 0x16, 0xfb, 0x82, 0x50, 0x48,
	0x51, 0x8d, 0x57, 0x92, 0x4f, 0xc9, 0x87, 0xe4, 0x6a, 0x32, 0xb9, 0x2c, 0x15, 0xd3, 0x6f, 0xf7,
	0xec, 0xb5, 0x85, 0xb0, 0x5d, 0xde, 0x02, 0xea, 0x3c, 0xaa, 0x85, 0x4e, 0x20, 0x45, 0xd8, 0x5c,
	0xcc, 0xee, 0x86, 0x31, 0x5c, 0x5c, 0xe1, 0x7e, 0xec, 0x55, 0x82, 0x90, 0xaf, 0x38, 0x27, 0x4b,
	0x37, 0x4f, 0x36, 0xc9, 0x49, 0x22, 0x27, 0xe7, 0xfc, 0xd8, 0xbb, 0x27, 0x90, 0x8e, 0xf0, 0xa3,
	0xdd, 0x97, 0x7f, 0xbd, 0x6e, 0x6f, 0xe1, 0xf6, 0xfe, 0xa5, 0x51, 0x44, 0xd5, 0xdf, 0x16, 0x13,
	0x90, 0x2d, 0xc1, 0x0d, 0x39, 0x5f, 0x24, 0x43, 0xc7, 0xb7, 0x79, 0xa8, 0x31, 0x7e, 0x87, 0xc6,
	0xb1, 0x8c, 0xf1, 0x3e, 0x44, 0xd9, 0x2c, 0x0c, 0x75, 0xe3, 0xfa, 0x1e, 0x5d, 0x83, 0x3c, 0x2b,
	0x99, 0x87, 0x91, 0x44, 0x52, 0x8b, 0x23, 0x29, 0x3c, 0xdf, 0xf2, 0xb8, 0x46, 0xf3, 0x43, 0xa2,
	0x29, 0x2e, 0x0d, 0x2b, 0x6c, 0x36, 0xa5, 0x18, 0x83, 0x7e, 0xf5, 0x4d, 0x9d, 0xd7, 0x5c, 0x8d,
	0xe1, 0x0a, 0x06, 0x92, 0xae, 0x67, 0xc7, 0x61, 0x5c, 0x5d, 0x9f, 0xb0, 0xdc, 0x98, 0x67, 0x23,
	0xb9, 0xad, 0xa3, 0xe7, 0xb8, 0x5a, 0x46, 0xb2, 0x1f, 0x4f, 0xf7, 0x26, 0xe1, 0x8c, 0xa5, 0x82,
	0x4c, 0x4c, 0x99, 0x2a, 0xda, 0x5c, 0x4a, 0x1e, 0x46, 0x15, 0xcb, 0xed, 0x14, 0xde, 0x61, 0xc7,
	0x4d, 0x8d, 0x67, 0x37, 0xf2, 0x55, 0x9c, 0x6f, 0x92, 0x33, 0xae, 0xcb, 0x96, 0xe1, 0xc6, 0x0e,
	0x4f, 0x85, 0x81, 0xf3, 0x1c, 0x3a, 0xc7, 0x77, 0x3c, 0x19, 0x4a, 0xbb, 0x08, 0xf4, 0x7d, 0x5a,
	0x4b, 0x03, 0xe7, 0xeb, 0xe8, 0x2c, 0x21, 0x4b, 0x25, 0x55, 0xc6, 0xa3, 0x30, 0x7a, 0x82, 0x87,
	0x55, 0x11, 0xf1, 0x0a, 0x7f, 0x34, 0xb6, 0x5c, 0x03, 0xdd, 0x79, 0xd4, 0x8d, 0x20, 0x38, 0xa7,
	0x38, 0xe5, 0x3a, 0x00, 0xfd, 0x2b, 0x56, 0x8d, 0x1b, 0x28, 0x2e, 0xa0, 0xa2, 0x4f, 0xad, 0x57,
	0xe8, 0x0c, 0x0c, 0xda, 0xa2, 0x79, 0x4b, 0x06, 0xf8, 0x45, 0xc4, 0x07, 0x88, 0x41, 0x45, 0x20,
	0x82, 0xd8, 0xb5, 0xa4, 0x49, 0x04, 0x6f, 0x90, 0x82, 0x18, 0x54, 0x74, 0x91, 0xd6, 0x37, 0x49,
	0x11, 0x65, 0xf2, 0x39, 0x0d, 0x03, 0xc2, 0x77, 0xd7, 0x84, 0x6f, 0x12, 0xc4, 0x5b, 0x68, 0x00,
	0x44, 0x94, 0x60, 0x0a, 0x8a, 0xa6, 0x85, 0x78, 0x7b, 0x83, 0xb6, 0x07, 0x55, 0x60, 0x1e, 0x46,
	0xa8, 0x41, 0x39, 0xc2, 0x37, 0x50, 0xbc, 0x83, 0x8a, 0xe1, 0x0c, 0x86, 0xb7, 0x21, 0x79, 0x24,
	0x6d, 0x6e, 0x22, 0x79, 0x97, 0x6e, 0x03, 0x11, 0x4c, 0x65, 0x95, 0xfb, 0xb5, 0x55, 0x33, 0xc3,
	0x25, 0x4a, 0x25, 0x31, 0x4a, 0x31, 0x0b, 0x43, 0x9e, 0x15, 0x46, 0xab, 0x96, 0x6b, 0x54, 0x8e,
	0xf7, 0xd0, 0x31, 0x98, 0x42, 0x98, 0x91, 0xd8, 0xef, 0x46, 0xf3, 0x3e, 0x65, 0x24, 0x83, 0xe1,
	0xd6, 0x8b, 0xa4, 0x55, 0x75, 0x79, 0xa5, 0x1b, 0xdb, 0x07, 0xb4, 0xf5, 0x9a, 0xec, 0x42, 0xd6,
	0x38, 0x05, 0xc5, 0xc8, 0x39, 0x65, 0xa4, 0xf9, 0x90, 0x2a, 0x9d, 0x00, 0x0a, 0x7e, 0x10, 0x6e,
	0xea, 0x38, 0x26, 0x0c, 0x64, 0x1f, 0xa1, 0x6c, 0xa2, 0xc3, 0xa8, 0xc0, 0x96, 0xd0, 0xad, 0xf2,
	0x63, 0x6a, 0x09, 0xbc, 0xcd, 0xb5, 0x08, 0xe3, 0xb1, 0x1f, 0x59, 0x2b, 0xdd, 0x65, 0xed, 0x13,
	0xca, 0x5a, 0x93, 0xcd, 0x65, 0xed, 0x18, 0x4c, 0xa0, 0xb1, 0xbb, 0xba, 0x7e, 0x4a, 0x8d, 0xb5,
	0x49, 0x2f, 0xe7, 0xab, 0xfb, 0x10, 0xec, 0x49, 0xd3, 0x79, 0x52, 0x72, 0x3f, 0x52, 0x4c, 0xc5,
	0xb3, 0x02, 0x03, 0xf3, 0x65, 0x34, 0x53, 0xc7, 0x9f, 0x4b, 0x05, 0x0b, 0x56, 0xa0, 0xe4, 0x0f,
	0xc0, 0x6e, 0x92, 0xc7, 0x7e, 0xc8, 0x6b, 0xc2, 0xf6, 0x9d, 0x53, 0xbc, 0x6e, 0xa0, 0xfe, 0xac,
	0xad, 0x54, 0xcb, 0x19, 0x5c, 0x99, 0x8f, 0xc0, 0xf5, 0xe9, 0x59, 0xa5, 0xe2, 0x78, 0x81, 0x08,
	0xa5, 0xc6, 0xf8, 0x39, 0x55, 0x2a, 0xe5, 0x8e, 0x24, 0x18, 0x9b, 0x83, 0xe1, 0xe4, 0xa3, 0xe9,
	0x23, 0xf9, 0x05, 0x8a, 0x86, 0x5a, 0x14, 0x36, 0x8e, 0x9a, 0xf0, 0x02, 0x2b, 0x34, 0xe9, 0x7f,
	0x5f, 0x52, 0xe3, 0x40, 0x04, 0x1b, 0x87, 0x5c, 0x0b, 0xb8, 0x9a, 0xf6, 0x06, 0x86, 0xaf, 0xa8,
	0x71, 0x10, 0x83, 0x0a, 0x3a, 0x30, 0x18, 0x28, 0xbe, 0x26, 0x05, 0x31, 0x4a, 0x71, 0x6f, 0x6b,
	0xd0, 0x86, 0xdc, 0x76, 0x22, 0x19, 0x5a, 0x6a, 0xb5, 0x46, 0xf5, 0xcd, 0x46, 0xfe, 0x10, 0xb6,
	0x94, 0x41, 0xd9, 0x51, 0x18, 0x69, 0x3b, 0x62, 0x94, 0x6e, 0xdd, 0x61, 0x5b, 0xe0, 0x51, 0x64,
	0xd9, 0xa9, 0xf0, 0xf1, 0x2d, 0x6c, 0x46, 0xf9, 0x13, 0x06, 0xbb, 0x4b, 0xd5, 0x3d, 0x7f, 0x0e,
	0xd0, 0xcb, 0x4e, 0x6f, 0xa5, 0xa5, 0xcf, 0x1d, 0x03, 0xd8, 0x61, 0x18, 0xca, 0x9d, 0x01, 0xf4,
	0xaa, 0x27, 0x50, 0x35, 0x98, 0x3d, 0x02, 0xb0, 0xfd, 0xd0, 0xab, 0xe6, 0xb9, 0x1e, 0x7f, 0x12,
	0xf1, 0x64, 0x39, 0x3b, 0x08, 0xfd, 0x34, 0xc7, 0xf5, 0xe8, 0x53, 0x88, 0xa6, 0x88, 0xc2, 0x69,
	0x86, 0xeb, 0xf1, 0xa7, 0x09, 0x27, 0x44, 0xe1, 0xe6, 0x29, 0xfc, 0xf6, 0xd9, 0x5e, 0xec, 0xc3,
	0x94, 0xbb, 0x29, 0xe8, 0xc3, 0xe1, 0xad, 0xa7, 0x9f, 0xc1, 0x1f, 0x27, 0x82, 0xdd, 0x09, 0xbb,
	0x0c, 0x13, 0xfe, 0x1c, 0xa2, 0xcd, 0xf5, 0x6c, 0x16, 0x06, 0x32, 0x03, 0x5b, 0x8f, 0x3f, 0x8f,
	0x78, 0x96, 0x52, 0xa1, 0xe3, 0xc0, 0xd6, 0x0b, 0x5e, 0xa0, 0xd0, 0x91, 0x50, 0x69, 0xa3, 0x59,
	0xad, 0xa7, 0xcf, 0x50, 0xd6, 0x09, 0x61, 0xd3, 0x50, 0x4c, 0xfb, 0xaf, 0x9e, 0x7f, 0x11, 0xf9,
	0x16, 0xa3, 0x32, 0x90, 0xe9, 0xff, 0x7a, 0xc5, 0x4b, 0x94, 0x81, 0x0c, 0xa5, 0xb6, 0x51, 0xfb,
	0x4c, 0xd7, 0x9b, 0x5e, 0xa6, 0x6d, 0xd4, 0x36, 0xd2, 0x55, 0x35, 0x93, 0x36, 0xa8, 0x57, 0xbc,
	0x42, 0xd5, 0x4c, 0xd6, 0xab, 0x30, 0xda, 0x87, 0xa4, 0xde, 0xf1, 0x2a, 0x85, 0xd1, 0x36, 0x23,
	0xd9, 0x22, 0x94, 0x76, 0x0e, 0x48, 0xbd, 0xef, 0x35, 0xf4, 0x8d, 0xee, 0x98, 0x8f, 0xec, 0x7e,
	0x98, 0xe8, 0x3c, 0x1c, 0xf5, 0xd6, 0xb3, 0x5b, 0x6d, 0xaf, 0x33, 0xd9, 0xd9, 0xc8, 0x8e, 0xb5,
	0xba, 0x6c, 0x76, 0x30, 0xea, 0xb5, 0xe7, 0xb6, 0xf2, 0x8d, 0x36, 0x3b, 0x17, 0xd9, 0x0c, 0x40,
	0x6b, 0x26, 0xe9, 0x5d, 0xe7, 0xd1, 0x95, 0x81, 0xd4, 0xd6, 0xc0, 0x91, 0xa4, 0xe7, 0x2f, 0xd0,
	0xd6, 0x40, 0x42, 0x6d, 0x0d, 0x9a, 0x46, 0x7a, 0xfa, 0x22, 0x6d, 0x0d, 0x42, 0xd8, 0x14, 0xf4,
	0xfb, 0xb1, 0xeb, 0xaa, 0x67, 0xab, 0x74, 0x4b, 0x87, 0x71, 0xc3, 0xdd, 0x3a, 0xc1, 0xbf, 0x6f,
	0x23, 0x4c, 0x00, 0xdb, 0x0f, 0xbb, 0xb8, 0x57, 0xe5, 0x75, 0x1d, 0xf9, 0xc7, 0x36, 0xf5, 0x13,
	0xb5, 0x9a, 0x4d, 0x03, 0x34, 0x5f, 0xa6, 0x55, 0x14, 0x3a, 0xf6, 0xcf, 0xed, 0xe6, 0x7b, 0x7d,
	0x06, 0x69, 0x09, 0x92, 0xb7, 0x71, 0x8d, 0x60, 0x23, 0x2f, 0x48, 0x5e, 0xc0, 0x0f, 0x40, 0xdf,
	0xc3, 0x91, 0xf0, 0xa5, 0x65, 0xeb, 0xe8, 0xbf, 0x90, 0xa6, 0xf5, 0x2a, 0x61, 0x9e, 0x08, 0xb9,
	0xb4, 0xec, 0x48, 0xc7, 0xfe, 0x8d, 0x6c, 0x0a, 0x28, 0xb8, 0x66, 0x45, 0xd2, 0xe4, 0xbe, 0xff,
	0x21, 0x98, 0x00, 0x15, 0xb4, 0xba, 0x7e, 0x84, 0xaf, 0xe9, 0xd8, 0x4d, 0x0a, 0x1a, 0xd7, 0xb3,
	0x83, 0x50, 0x54, 0x97, 0xc9, 0xff, 0x21, 0x74, 0xf0, 0xbf, 0x08, 0xb7, 0x08, 0xf5, 0xcb, 0x91,
	0xac, 0x4b, 0x47, 0x9f, 0xec, 0xff, 0xb0, 0xd2, 0xb4, 0x9e, 0xcd, 0xc0, 0x40, 0x24, 0xeb, 0xf5,
	0x18, 0x4f, 0x34, 0x1a, 0xfc, 0xff, 0xed, 0xf4, 0x25, 0x37, 0x65, 0x0e, 0x2d, 0x5c, 0x5d, 0x2f,
	0xf7, 0xfc, 0xb4, 0x5e, 0xee, 0xd9, 0x5c, 0x2f, 0x17, 0x1e, 0x6b, 0x94, 0x0b, 0x97, 0x1a, 0xe5,
	0xc2, 0x95, 0x46, 0xb9, 0x70, 0xb5, 0x51, 0x2e, 0xfc, 0xdc, 0x28, 0x17, 0x7e, 0x6b, 0x94, 0x7b,
	0x36, 0x1b, 0xe5, 0xc2, 0x99, 0x5f, 0xca, 0x3d, 0x30, 0x56, 0x13, 0x5e, 0xfb, 0x8f, 0x1c, 0x82,
	0x79, 0x31, 0x2f, 0x16, 0x93, 0x1d, 0x77, 0x2d, 0x00, 0x00, 0xff, 0xff, 0xac, 0xca, 0x18, 0x3d,
	0x9f, 0x13, 0x00, 0x00,
}
