// flow-typed signature: e6f8f7a17f4fc0cac7dc4506a3494e8b
// flow-typed version: <<STUB>>/@types/google-protobuf_v^3.2.6/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/google-protobuf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@types/google-protobuf" {
  declare module.exports: any;
}
