// flow-typed signature: 8ed9c83439f4bba41e061aa0ec2fd2f9
// flow-typed version: <<STUB>>/basictracer_v^2.2.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'basictracer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "basictracer" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "basictracer/dist/__tests__/propagation-test" {
  declare module.exports: any;
}

declare module "basictracer/dist/__tests__/span-test" {
  declare module.exports: any;
}

declare module "basictracer/dist/__tests__/tracer-test" {
  declare module.exports: any;
}

declare module "basictracer/dist/constants" {
  declare module.exports: any;
}

declare module "basictracer/dist/index" {
  declare module.exports: any;
}

declare module "basictracer/dist/propagation" {
  declare module.exports: any;
}

declare module "basictracer/dist/span" {
  declare module.exports: any;
}

declare module "basictracer/dist/tracer" {
  declare module.exports: any;
}

// Filename aliases
declare module "basictracer/dist/__tests__/propagation-test.js" {
  declare module.exports: $Exports<
    "basictracer/dist/__tests__/propagation-test"
  >;
}
declare module "basictracer/dist/__tests__/span-test.js" {
  declare module.exports: $Exports<"basictracer/dist/__tests__/span-test">;
}
declare module "basictracer/dist/__tests__/tracer-test.js" {
  declare module.exports: $Exports<"basictracer/dist/__tests__/tracer-test">;
}
declare module "basictracer/dist/constants.js" {
  declare module.exports: $Exports<"basictracer/dist/constants">;
}
declare module "basictracer/dist/index.js" {
  declare module.exports: $Exports<"basictracer/dist/index">;
}
declare module "basictracer/dist/propagation.js" {
  declare module.exports: $Exports<"basictracer/dist/propagation">;
}
declare module "basictracer/dist/span.js" {
  declare module.exports: $Exports<"basictracer/dist/span">;
}
declare module "basictracer/dist/tracer.js" {
  declare module.exports: $Exports<"basictracer/dist/tracer">;
}
