// flow-typed signature: 3c07feea9dbff6e0c633f48f498cfe16
// flow-typed version: <<STUB>>/cerebral_vbeta/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cerebral'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "cerebral" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "cerebral/angularjs" {
  declare module.exports: any;
}

declare module "cerebral/devtools" {
  declare module.exports: any;
}

declare module "cerebral/inferno" {
  declare module.exports: any;
}

declare module "cerebral/lib/Compute" {
  declare module.exports: any;
}

declare module "cerebral/lib/Controller" {
  declare module.exports: any;
}

declare module "cerebral/lib/DependencyStore" {
  declare module.exports: any;
}

declare module "cerebral/lib/DependencyTracker" {
  declare module.exports: any;
}

declare module "cerebral/lib/devtools/index" {
  declare module.exports: any;
}

declare module "cerebral/lib/index" {
  declare module.exports: any;
}

declare module "cerebral/lib/Model" {
  declare module.exports: any;
}

declare module "cerebral/lib/Module" {
  declare module.exports: any;
}

declare module "cerebral/lib/operators/concat" {
  declare module.exports: any;
}

declare module "cerebral/lib/operators/debounce" {
  declare module.exports: any;
}

declare module "cerebral/lib/operators/equals" {
  declare module.exports: any;
}

declare module "cerebral/lib/operators/increment" {
  declare module.exports: any;
}

declare module "cerebral/lib/operators/index" {
  declare module.exports: any;
}

declare module "cerebral/lib/operators/input" {
  declare module.exports: any;
}

declare module "cerebral/lib/operators/merge" {
  declare module.exports: any;
}

declare module "cerebral/lib/operators/pop" {
  declare module.exports: any;
}

declare module "cerebral/lib/operators/push" {
  declare module.exports: any;
}

declare module "cerebral/lib/operators/set" {
  declare module.exports: any;
}

declare module "cerebral/lib/operators/shift" {
  declare module.exports: any;
}

declare module "cerebral/lib/operators/signal" {
  declare module.exports: any;
}

declare module "cerebral/lib/operators/splice" {
  declare module.exports: any;
}

declare module "cerebral/lib/operators/state" {
  declare module.exports: any;
}

declare module "cerebral/lib/operators/string" {
  declare module.exports: any;
}

declare module "cerebral/lib/operators/toggle" {
  declare module.exports: any;
}

declare module "cerebral/lib/operators/unset" {
  declare module.exports: any;
}

declare module "cerebral/lib/operators/unshift" {
  declare module.exports: any;
}

declare module "cerebral/lib/operators/wait" {
  declare module.exports: any;
}

declare module "cerebral/lib/operators/when" {
  declare module.exports: any;
}

declare module "cerebral/lib/Provide" {
  declare module.exports: any;
}

declare module "cerebral/lib/providers/Controller" {
  declare module.exports: any;
}

declare module "cerebral/lib/providers/Debugger" {
  declare module.exports: any;
}

declare module "cerebral/lib/providers/index" {
  declare module.exports: any;
}

declare module "cerebral/lib/providers/Recorder" {
  declare module.exports: any;
}

declare module "cerebral/lib/providers/Resolve" {
  declare module.exports: any;
}

declare module "cerebral/lib/providers/State" {
  declare module.exports: any;
}

declare module "cerebral/lib/providers/VerifyProps" {
  declare module.exports: any;
}

declare module "cerebral/lib/tags/index" {
  declare module.exports: any;
}

declare module "cerebral/lib/tags/Tag" {
  declare module.exports: any;
}

declare module "cerebral/lib/test/index" {
  declare module.exports: any;
}

declare module "cerebral/lib/UniversalController" {
  declare module.exports: any;
}

declare module "cerebral/lib/utils" {
  declare module.exports: any;
}

declare module "cerebral/lib/views/angularjs/connect" {
  declare module.exports: any;
}

declare module "cerebral/lib/views/angularjs/index" {
  declare module.exports: any;
}

declare module "cerebral/lib/views/angularjs/module" {
  declare module.exports: any;
}

declare module "cerebral/lib/views/inferno/connect" {
  declare module.exports: any;
}

declare module "cerebral/lib/views/inferno/Container" {
  declare module.exports: any;
}

declare module "cerebral/lib/views/inferno/Hoc" {
  declare module.exports: any;
}

declare module "cerebral/lib/views/inferno/index" {
  declare module.exports: any;
}

declare module "cerebral/lib/views/inferno/StateContainer" {
  declare module.exports: any;
}

declare module "cerebral/lib/views/preact/connect" {
  declare module.exports: any;
}

declare module "cerebral/lib/views/preact/Container" {
  declare module.exports: any;
}

declare module "cerebral/lib/views/preact/Hoc" {
  declare module.exports: any;
}

declare module "cerebral/lib/views/preact/index" {
  declare module.exports: any;
}

declare module "cerebral/lib/views/preact/StateContainer" {
  declare module.exports: any;
}

declare module "cerebral/lib/views/react/connect" {
  declare module.exports: any;
}

declare module "cerebral/lib/views/react/Container" {
  declare module.exports: any;
}

declare module "cerebral/lib/views/react/Hoc" {
  declare module.exports: any;
}

declare module "cerebral/lib/views/react/index" {
  declare module.exports: any;
}

declare module "cerebral/lib/views/react/StateContainer" {
  declare module.exports: any;
}

declare module "cerebral/lib/views/View" {
  declare module.exports: any;
}

declare module "cerebral/lib/views/vue/connect" {
  declare module.exports: any;
}

declare module "cerebral/lib/views/vue/Container" {
  declare module.exports: any;
}

declare module "cerebral/lib/views/vue/index" {
  declare module.exports: any;
}

declare module "cerebral/operators" {
  declare module.exports: any;
}

declare module "cerebral/preact" {
  declare module.exports: any;
}

declare module "cerebral/providers" {
  declare module.exports: any;
}

declare module "cerebral/react" {
  declare module.exports: any;
}

declare module "cerebral/tags" {
  declare module.exports: any;
}

declare module "cerebral/test" {
  declare module.exports: any;
}

declare module "cerebral/typescript/typescript.spec" {
  declare module.exports: any;
}

declare module "cerebral/vue" {
  declare module.exports: any;
}

// Filename aliases
declare module "cerebral/angularjs.js" {
  declare module.exports: $Exports<"cerebral/angularjs">;
}
declare module "cerebral/devtools.js" {
  declare module.exports: $Exports<"cerebral/devtools">;
}
declare module "cerebral/index" {
  declare module.exports: $Exports<"cerebral">;
}
declare module "cerebral/index.js" {
  declare module.exports: $Exports<"cerebral">;
}
declare module "cerebral/inferno.js" {
  declare module.exports: $Exports<"cerebral/inferno">;
}
declare module "cerebral/lib/Compute.js" {
  declare module.exports: $Exports<"cerebral/lib/Compute">;
}
declare module "cerebral/lib/Controller.js" {
  declare module.exports: $Exports<"cerebral/lib/Controller">;
}
declare module "cerebral/lib/DependencyStore.js" {
  declare module.exports: $Exports<"cerebral/lib/DependencyStore">;
}
declare module "cerebral/lib/DependencyTracker.js" {
  declare module.exports: $Exports<"cerebral/lib/DependencyTracker">;
}
declare module "cerebral/lib/devtools/index.js" {
  declare module.exports: $Exports<"cerebral/lib/devtools/index">;
}
declare module "cerebral/lib/index.js" {
  declare module.exports: $Exports<"cerebral/lib/index">;
}
declare module "cerebral/lib/Model.js" {
  declare module.exports: $Exports<"cerebral/lib/Model">;
}
declare module "cerebral/lib/Module.js" {
  declare module.exports: $Exports<"cerebral/lib/Module">;
}
declare module "cerebral/lib/operators/concat.js" {
  declare module.exports: $Exports<"cerebral/lib/operators/concat">;
}
declare module "cerebral/lib/operators/debounce.js" {
  declare module.exports: $Exports<"cerebral/lib/operators/debounce">;
}
declare module "cerebral/lib/operators/equals.js" {
  declare module.exports: $Exports<"cerebral/lib/operators/equals">;
}
declare module "cerebral/lib/operators/increment.js" {
  declare module.exports: $Exports<"cerebral/lib/operators/increment">;
}
declare module "cerebral/lib/operators/index.js" {
  declare module.exports: $Exports<"cerebral/lib/operators/index">;
}
declare module "cerebral/lib/operators/input.js" {
  declare module.exports: $Exports<"cerebral/lib/operators/input">;
}
declare module "cerebral/lib/operators/merge.js" {
  declare module.exports: $Exports<"cerebral/lib/operators/merge">;
}
declare module "cerebral/lib/operators/pop.js" {
  declare module.exports: $Exports<"cerebral/lib/operators/pop">;
}
declare module "cerebral/lib/operators/push.js" {
  declare module.exports: $Exports<"cerebral/lib/operators/push">;
}
declare module "cerebral/lib/operators/set.js" {
  declare module.exports: $Exports<"cerebral/lib/operators/set">;
}
declare module "cerebral/lib/operators/shift.js" {
  declare module.exports: $Exports<"cerebral/lib/operators/shift">;
}
declare module "cerebral/lib/operators/signal.js" {
  declare module.exports: $Exports<"cerebral/lib/operators/signal">;
}
declare module "cerebral/lib/operators/splice.js" {
  declare module.exports: $Exports<"cerebral/lib/operators/splice">;
}
declare module "cerebral/lib/operators/state.js" {
  declare module.exports: $Exports<"cerebral/lib/operators/state">;
}
declare module "cerebral/lib/operators/string.js" {
  declare module.exports: $Exports<"cerebral/lib/operators/string">;
}
declare module "cerebral/lib/operators/toggle.js" {
  declare module.exports: $Exports<"cerebral/lib/operators/toggle">;
}
declare module "cerebral/lib/operators/unset.js" {
  declare module.exports: $Exports<"cerebral/lib/operators/unset">;
}
declare module "cerebral/lib/operators/unshift.js" {
  declare module.exports: $Exports<"cerebral/lib/operators/unshift">;
}
declare module "cerebral/lib/operators/wait.js" {
  declare module.exports: $Exports<"cerebral/lib/operators/wait">;
}
declare module "cerebral/lib/operators/when.js" {
  declare module.exports: $Exports<"cerebral/lib/operators/when">;
}
declare module "cerebral/lib/Provide.js" {
  declare module.exports: $Exports<"cerebral/lib/Provide">;
}
declare module "cerebral/lib/providers/Controller.js" {
  declare module.exports: $Exports<"cerebral/lib/providers/Controller">;
}
declare module "cerebral/lib/providers/Debugger.js" {
  declare module.exports: $Exports<"cerebral/lib/providers/Debugger">;
}
declare module "cerebral/lib/providers/index.js" {
  declare module.exports: $Exports<"cerebral/lib/providers/index">;
}
declare module "cerebral/lib/providers/Recorder.js" {
  declare module.exports: $Exports<"cerebral/lib/providers/Recorder">;
}
declare module "cerebral/lib/providers/Resolve.js" {
  declare module.exports: $Exports<"cerebral/lib/providers/Resolve">;
}
declare module "cerebral/lib/providers/State.js" {
  declare module.exports: $Exports<"cerebral/lib/providers/State">;
}
declare module "cerebral/lib/providers/VerifyProps.js" {
  declare module.exports: $Exports<"cerebral/lib/providers/VerifyProps">;
}
declare module "cerebral/lib/tags/index.js" {
  declare module.exports: $Exports<"cerebral/lib/tags/index">;
}
declare module "cerebral/lib/tags/Tag.js" {
  declare module.exports: $Exports<"cerebral/lib/tags/Tag">;
}
declare module "cerebral/lib/test/index.js" {
  declare module.exports: $Exports<"cerebral/lib/test/index">;
}
declare module "cerebral/lib/UniversalController.js" {
  declare module.exports: $Exports<"cerebral/lib/UniversalController">;
}
declare module "cerebral/lib/utils.js" {
  declare module.exports: $Exports<"cerebral/lib/utils">;
}
declare module "cerebral/lib/views/angularjs/connect.js" {
  declare module.exports: $Exports<"cerebral/lib/views/angularjs/connect">;
}
declare module "cerebral/lib/views/angularjs/index.js" {
  declare module.exports: $Exports<"cerebral/lib/views/angularjs/index">;
}
declare module "cerebral/lib/views/angularjs/module.js" {
  declare module.exports: $Exports<"cerebral/lib/views/angularjs/module">;
}
declare module "cerebral/lib/views/inferno/connect.js" {
  declare module.exports: $Exports<"cerebral/lib/views/inferno/connect">;
}
declare module "cerebral/lib/views/inferno/Container.js" {
  declare module.exports: $Exports<"cerebral/lib/views/inferno/Container">;
}
declare module "cerebral/lib/views/inferno/Hoc.js" {
  declare module.exports: $Exports<"cerebral/lib/views/inferno/Hoc">;
}
declare module "cerebral/lib/views/inferno/index.js" {
  declare module.exports: $Exports<"cerebral/lib/views/inferno/index">;
}
declare module "cerebral/lib/views/inferno/StateContainer.js" {
  declare module.exports: $Exports<"cerebral/lib/views/inferno/StateContainer">;
}
declare module "cerebral/lib/views/preact/connect.js" {
  declare module.exports: $Exports<"cerebral/lib/views/preact/connect">;
}
declare module "cerebral/lib/views/preact/Container.js" {
  declare module.exports: $Exports<"cerebral/lib/views/preact/Container">;
}
declare module "cerebral/lib/views/preact/Hoc.js" {
  declare module.exports: $Exports<"cerebral/lib/views/preact/Hoc">;
}
declare module "cerebral/lib/views/preact/index.js" {
  declare module.exports: $Exports<"cerebral/lib/views/preact/index">;
}
declare module "cerebral/lib/views/preact/StateContainer.js" {
  declare module.exports: $Exports<"cerebral/lib/views/preact/StateContainer">;
}
declare module "cerebral/lib/views/react/connect.js" {
  declare module.exports: $Exports<"cerebral/lib/views/react/connect">;
}
declare module "cerebral/lib/views/react/Container.js" {
  declare module.exports: $Exports<"cerebral/lib/views/react/Container">;
}
declare module "cerebral/lib/views/react/Hoc.js" {
  declare module.exports: $Exports<"cerebral/lib/views/react/Hoc">;
}
declare module "cerebral/lib/views/react/index.js" {
  declare module.exports: $Exports<"cerebral/lib/views/react/index">;
}
declare module "cerebral/lib/views/react/StateContainer.js" {
  declare module.exports: $Exports<"cerebral/lib/views/react/StateContainer">;
}
declare module "cerebral/lib/views/View.js" {
  declare module.exports: $Exports<"cerebral/lib/views/View">;
}
declare module "cerebral/lib/views/vue/connect.js" {
  declare module.exports: $Exports<"cerebral/lib/views/vue/connect">;
}
declare module "cerebral/lib/views/vue/Container.js" {
  declare module.exports: $Exports<"cerebral/lib/views/vue/Container">;
}
declare module "cerebral/lib/views/vue/index.js" {
  declare module.exports: $Exports<"cerebral/lib/views/vue/index">;
}
declare module "cerebral/operators.js" {
  declare module.exports: $Exports<"cerebral/operators">;
}
declare module "cerebral/preact.js" {
  declare module.exports: $Exports<"cerebral/preact">;
}
declare module "cerebral/providers.js" {
  declare module.exports: $Exports<"cerebral/providers">;
}
declare module "cerebral/react.js" {
  declare module.exports: $Exports<"cerebral/react">;
}
declare module "cerebral/tags.js" {
  declare module.exports: $Exports<"cerebral/tags">;
}
declare module "cerebral/test.js" {
  declare module.exports: $Exports<"cerebral/test">;
}
declare module "cerebral/typescript/typescript.spec.js" {
  declare module.exports: $Exports<"cerebral/typescript/typescript.spec">;
}
declare module "cerebral/vue.js" {
  declare module.exports: $Exports<"cerebral/vue">;
}
