// flow-typed signature: bf3f33b8bec0dd53b971dd4213126e1a
// flow-typed version: <<STUB>>/cytoscape-dagre_v^1.6.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cytoscape-dagre'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "cytoscape-dagre" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "cytoscape-dagre/cytoscape-dagre" {
  declare module.exports: any;
}

declare module "cytoscape-dagre/gulpfile" {
  declare module.exports: any;
}

// Filename aliases
declare module "cytoscape-dagre/cytoscape-dagre.js" {
  declare module.exports: $Exports<"cytoscape-dagre/cytoscape-dagre">;
}
declare module "cytoscape-dagre/gulpfile.js" {
  declare module.exports: $Exports<"cytoscape-dagre/gulpfile">;
}
