// flow-typed signature: a8ef31d120b8e4564cc75edd9f40dfeb
// flow-typed version: <<STUB>>/cytoscape_v^3.1.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cytoscape'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "cytoscape" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "cytoscape/dist/cytoscape" {
  declare module.exports: any;
}

declare module "cytoscape/dist/cytoscape.min" {
  declare module.exports: any;
}

declare module "cytoscape/src/-preamble" {
  declare module.exports: any;
}

declare module "cytoscape/src/animation" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/algorithms/a-star" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/algorithms/bellman-ford" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/algorithms/betweenness-centrality" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/algorithms/bfs-dfs" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/algorithms/closeness-centrality" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/algorithms/degree-centrality" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/algorithms/dijkstra" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/algorithms/floyd-warshall" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/algorithms/index" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/algorithms/kerger-stein" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/algorithms/kruskal" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/algorithms/page-rank" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/animation" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/class" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/comparators" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/compounds" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/data" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/degree" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/dimensions" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/element" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/events" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/filter" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/group" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/index" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/iteration" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/layout" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/style" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/switch-functions" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/traversing" {
  declare module.exports: any;
}

declare module "cytoscape/src/collection/zsort" {
  declare module.exports: any;
}

declare module "cytoscape/src/core/add-remove" {
  declare module.exports: any;
}

declare module "cytoscape/src/core/animation" {
  declare module.exports: any;
}

declare module "cytoscape/src/core/events" {
  declare module.exports: any;
}

declare module "cytoscape/src/core/export" {
  declare module.exports: any;
}

declare module "cytoscape/src/core/index" {
  declare module.exports: any;
}

declare module "cytoscape/src/core/layout" {
  declare module.exports: any;
}

declare module "cytoscape/src/core/notification" {
  declare module.exports: any;
}

declare module "cytoscape/src/core/renderer" {
  declare module.exports: any;
}

declare module "cytoscape/src/core/search" {
  declare module.exports: any;
}

declare module "cytoscape/src/core/style" {
  declare module.exports: any;
}

declare module "cytoscape/src/core/viewport" {
  declare module.exports: any;
}

declare module "cytoscape/src/define" {
  declare module.exports: any;
}

declare module "cytoscape/src/event" {
  declare module.exports: any;
}

declare module "cytoscape/src/extension" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/index" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/layout/breadthfirst" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/layout/circle" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/layout/concentric" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/layout/cose" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/layout/grid" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/layout/index" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/layout/null" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/layout/preset" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/layout/random" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/base/arrow-shapes" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/base/coord-ele-math/coords" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/base/coord-ele-math/edge-arrows" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/base/coord-ele-math/edge-control-points" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/base/coord-ele-math/edge-endpoints" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/base/coord-ele-math/edge-projection" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/base/coord-ele-math/index" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/base/coord-ele-math/labels" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/base/coord-ele-math/nodes" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/base/coord-ele-math/rendered-style" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/base/coord-ele-math/z-ordering" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/base/images" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/base/index" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/base/load-listeners" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/base/node-shapes" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/base/redraw" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/canvas/arrow-shapes" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/canvas/drawing-edges" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/canvas/drawing-elements" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/canvas/drawing-images" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/canvas/drawing-label-text" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/canvas/drawing-nodes" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/canvas/drawing-redraw" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/canvas/drawing-shapes" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/canvas/ele-texture-cache" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/canvas/export-image" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/canvas/index" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/canvas/layered-texture-cache" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/canvas/node-shapes" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/canvas/texture-cache-defs" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/index" {
  declare module.exports: any;
}

declare module "cytoscape/src/extensions/renderer/null/index" {
  declare module.exports: any;
}

declare module "cytoscape/src/heap" {
  declare module.exports: any;
}

declare module "cytoscape/src/index" {
  declare module.exports: any;
}

declare module "cytoscape/src/is" {
  declare module.exports: any;
}

declare module "cytoscape/src/map" {
  declare module.exports: any;
}

declare module "cytoscape/src/math" {
  declare module.exports: any;
}

declare module "cytoscape/src/promise" {
  declare module.exports: any;
}

declare module "cytoscape/src/selector" {
  declare module.exports: any;
}

declare module "cytoscape/src/set" {
  declare module.exports: any;
}

declare module "cytoscape/src/style/apply" {
  declare module.exports: any;
}

declare module "cytoscape/src/style/bypass" {
  declare module.exports: any;
}

declare module "cytoscape/src/style/container" {
  declare module.exports: any;
}

declare module "cytoscape/src/style/get-for-ele" {
  declare module.exports: any;
}

declare module "cytoscape/src/style/index" {
  declare module.exports: any;
}

declare module "cytoscape/src/style/json" {
  declare module.exports: any;
}

declare module "cytoscape/src/style/parse" {
  declare module.exports: any;
}

declare module "cytoscape/src/style/properties" {
  declare module.exports: any;
}

declare module "cytoscape/src/style/string-sheet" {
  declare module.exports: any;
}

declare module "cytoscape/src/stylesheet" {
  declare module.exports: any;
}

declare module "cytoscape/src/util/colors" {
  declare module.exports: any;
}

declare module "cytoscape/src/util/index" {
  declare module.exports: any;
}

declare module "cytoscape/src/util/maps" {
  declare module.exports: any;
}

declare module "cytoscape/src/util/memoize" {
  declare module.exports: any;
}

declare module "cytoscape/src/util/regex" {
  declare module.exports: any;
}

declare module "cytoscape/src/util/sort" {
  declare module.exports: any;
}

declare module "cytoscape/src/util/strings" {
  declare module.exports: any;
}

declare module "cytoscape/src/util/timing" {
  declare module.exports: any;
}

declare module "cytoscape/src/version" {
  declare module.exports: any;
}

declare module "cytoscape/src/window" {
  declare module.exports: any;
}

// Filename aliases
declare module "cytoscape/dist/cytoscape.js" {
  declare module.exports: $Exports<"cytoscape/dist/cytoscape">;
}
declare module "cytoscape/dist/cytoscape.min.js" {
  declare module.exports: $Exports<"cytoscape/dist/cytoscape.min">;
}
declare module "cytoscape/src/-preamble.js" {
  declare module.exports: $Exports<"cytoscape/src/-preamble">;
}
declare module "cytoscape/src/animation.js" {
  declare module.exports: $Exports<"cytoscape/src/animation">;
}
declare module "cytoscape/src/collection/algorithms/a-star.js" {
  declare module.exports: $Exports<
    "cytoscape/src/collection/algorithms/a-star"
  >;
}
declare module "cytoscape/src/collection/algorithms/bellman-ford.js" {
  declare module.exports: $Exports<
    "cytoscape/src/collection/algorithms/bellman-ford"
  >;
}
declare module "cytoscape/src/collection/algorithms/betweenness-centrality.js" {
  declare module.exports: $Exports<
    "cytoscape/src/collection/algorithms/betweenness-centrality"
  >;
}
declare module "cytoscape/src/collection/algorithms/bfs-dfs.js" {
  declare module.exports: $Exports<
    "cytoscape/src/collection/algorithms/bfs-dfs"
  >;
}
declare module "cytoscape/src/collection/algorithms/closeness-centrality.js" {
  declare module.exports: $Exports<
    "cytoscape/src/collection/algorithms/closeness-centrality"
  >;
}
declare module "cytoscape/src/collection/algorithms/degree-centrality.js" {
  declare module.exports: $Exports<
    "cytoscape/src/collection/algorithms/degree-centrality"
  >;
}
declare module "cytoscape/src/collection/algorithms/dijkstra.js" {
  declare module.exports: $Exports<
    "cytoscape/src/collection/algorithms/dijkstra"
  >;
}
declare module "cytoscape/src/collection/algorithms/floyd-warshall.js" {
  declare module.exports: $Exports<
    "cytoscape/src/collection/algorithms/floyd-warshall"
  >;
}
declare module "cytoscape/src/collection/algorithms/index.js" {
  declare module.exports: $Exports<"cytoscape/src/collection/algorithms/index">;
}
declare module "cytoscape/src/collection/algorithms/kerger-stein.js" {
  declare module.exports: $Exports<
    "cytoscape/src/collection/algorithms/kerger-stein"
  >;
}
declare module "cytoscape/src/collection/algorithms/kruskal.js" {
  declare module.exports: $Exports<
    "cytoscape/src/collection/algorithms/kruskal"
  >;
}
declare module "cytoscape/src/collection/algorithms/page-rank.js" {
  declare module.exports: $Exports<
    "cytoscape/src/collection/algorithms/page-rank"
  >;
}
declare module "cytoscape/src/collection/animation.js" {
  declare module.exports: $Exports<"cytoscape/src/collection/animation">;
}
declare module "cytoscape/src/collection/class.js" {
  declare module.exports: $Exports<"cytoscape/src/collection/class">;
}
declare module "cytoscape/src/collection/comparators.js" {
  declare module.exports: $Exports<"cytoscape/src/collection/comparators">;
}
declare module "cytoscape/src/collection/compounds.js" {
  declare module.exports: $Exports<"cytoscape/src/collection/compounds">;
}
declare module "cytoscape/src/collection/data.js" {
  declare module.exports: $Exports<"cytoscape/src/collection/data">;
}
declare module "cytoscape/src/collection/degree.js" {
  declare module.exports: $Exports<"cytoscape/src/collection/degree">;
}
declare module "cytoscape/src/collection/dimensions.js" {
  declare module.exports: $Exports<"cytoscape/src/collection/dimensions">;
}
declare module "cytoscape/src/collection/element.js" {
  declare module.exports: $Exports<"cytoscape/src/collection/element">;
}
declare module "cytoscape/src/collection/events.js" {
  declare module.exports: $Exports<"cytoscape/src/collection/events">;
}
declare module "cytoscape/src/collection/filter.js" {
  declare module.exports: $Exports<"cytoscape/src/collection/filter">;
}
declare module "cytoscape/src/collection/group.js" {
  declare module.exports: $Exports<"cytoscape/src/collection/group">;
}
declare module "cytoscape/src/collection/index.js" {
  declare module.exports: $Exports<"cytoscape/src/collection/index">;
}
declare module "cytoscape/src/collection/iteration.js" {
  declare module.exports: $Exports<"cytoscape/src/collection/iteration">;
}
declare module "cytoscape/src/collection/layout.js" {
  declare module.exports: $Exports<"cytoscape/src/collection/layout">;
}
declare module "cytoscape/src/collection/style.js" {
  declare module.exports: $Exports<"cytoscape/src/collection/style">;
}
declare module "cytoscape/src/collection/switch-functions.js" {
  declare module.exports: $Exports<"cytoscape/src/collection/switch-functions">;
}
declare module "cytoscape/src/collection/traversing.js" {
  declare module.exports: $Exports<"cytoscape/src/collection/traversing">;
}
declare module "cytoscape/src/collection/zsort.js" {
  declare module.exports: $Exports<"cytoscape/src/collection/zsort">;
}
declare module "cytoscape/src/core/add-remove.js" {
  declare module.exports: $Exports<"cytoscape/src/core/add-remove">;
}
declare module "cytoscape/src/core/animation.js" {
  declare module.exports: $Exports<"cytoscape/src/core/animation">;
}
declare module "cytoscape/src/core/events.js" {
  declare module.exports: $Exports<"cytoscape/src/core/events">;
}
declare module "cytoscape/src/core/export.js" {
  declare module.exports: $Exports<"cytoscape/src/core/export">;
}
declare module "cytoscape/src/core/index.js" {
  declare module.exports: $Exports<"cytoscape/src/core/index">;
}
declare module "cytoscape/src/core/layout.js" {
  declare module.exports: $Exports<"cytoscape/src/core/layout">;
}
declare module "cytoscape/src/core/notification.js" {
  declare module.exports: $Exports<"cytoscape/src/core/notification">;
}
declare module "cytoscape/src/core/renderer.js" {
  declare module.exports: $Exports<"cytoscape/src/core/renderer">;
}
declare module "cytoscape/src/core/search.js" {
  declare module.exports: $Exports<"cytoscape/src/core/search">;
}
declare module "cytoscape/src/core/style.js" {
  declare module.exports: $Exports<"cytoscape/src/core/style">;
}
declare module "cytoscape/src/core/viewport.js" {
  declare module.exports: $Exports<"cytoscape/src/core/viewport">;
}
declare module "cytoscape/src/define.js" {
  declare module.exports: $Exports<"cytoscape/src/define">;
}
declare module "cytoscape/src/event.js" {
  declare module.exports: $Exports<"cytoscape/src/event">;
}
declare module "cytoscape/src/extension.js" {
  declare module.exports: $Exports<"cytoscape/src/extension">;
}
declare module "cytoscape/src/extensions/index.js" {
  declare module.exports: $Exports<"cytoscape/src/extensions/index">;
}
declare module "cytoscape/src/extensions/layout/breadthfirst.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/layout/breadthfirst"
  >;
}
declare module "cytoscape/src/extensions/layout/circle.js" {
  declare module.exports: $Exports<"cytoscape/src/extensions/layout/circle">;
}
declare module "cytoscape/src/extensions/layout/concentric.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/layout/concentric"
  >;
}
declare module "cytoscape/src/extensions/layout/cose.js" {
  declare module.exports: $Exports<"cytoscape/src/extensions/layout/cose">;
}
declare module "cytoscape/src/extensions/layout/grid.js" {
  declare module.exports: $Exports<"cytoscape/src/extensions/layout/grid">;
}
declare module "cytoscape/src/extensions/layout/index.js" {
  declare module.exports: $Exports<"cytoscape/src/extensions/layout/index">;
}
declare module "cytoscape/src/extensions/layout/null.js" {
  declare module.exports: $Exports<"cytoscape/src/extensions/layout/null">;
}
declare module "cytoscape/src/extensions/layout/preset.js" {
  declare module.exports: $Exports<"cytoscape/src/extensions/layout/preset">;
}
declare module "cytoscape/src/extensions/layout/random.js" {
  declare module.exports: $Exports<"cytoscape/src/extensions/layout/random">;
}
declare module "cytoscape/src/extensions/renderer/base/arrow-shapes.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/base/arrow-shapes"
  >;
}
declare module "cytoscape/src/extensions/renderer/base/coord-ele-math/coords.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/base/coord-ele-math/coords"
  >;
}
declare module "cytoscape/src/extensions/renderer/base/coord-ele-math/edge-arrows.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/base/coord-ele-math/edge-arrows"
  >;
}
declare module "cytoscape/src/extensions/renderer/base/coord-ele-math/edge-control-points.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/base/coord-ele-math/edge-control-points"
  >;
}
declare module "cytoscape/src/extensions/renderer/base/coord-ele-math/edge-endpoints.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/base/coord-ele-math/edge-endpoints"
  >;
}
declare module "cytoscape/src/extensions/renderer/base/coord-ele-math/edge-projection.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/base/coord-ele-math/edge-projection"
  >;
}
declare module "cytoscape/src/extensions/renderer/base/coord-ele-math/index.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/base/coord-ele-math/index"
  >;
}
declare module "cytoscape/src/extensions/renderer/base/coord-ele-math/labels.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/base/coord-ele-math/labels"
  >;
}
declare module "cytoscape/src/extensions/renderer/base/coord-ele-math/nodes.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/base/coord-ele-math/nodes"
  >;
}
declare module "cytoscape/src/extensions/renderer/base/coord-ele-math/rendered-style.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/base/coord-ele-math/rendered-style"
  >;
}
declare module "cytoscape/src/extensions/renderer/base/coord-ele-math/z-ordering.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/base/coord-ele-math/z-ordering"
  >;
}
declare module "cytoscape/src/extensions/renderer/base/images.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/base/images"
  >;
}
declare module "cytoscape/src/extensions/renderer/base/index.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/base/index"
  >;
}
declare module "cytoscape/src/extensions/renderer/base/load-listeners.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/base/load-listeners"
  >;
}
declare module "cytoscape/src/extensions/renderer/base/node-shapes.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/base/node-shapes"
  >;
}
declare module "cytoscape/src/extensions/renderer/base/redraw.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/base/redraw"
  >;
}
declare module "cytoscape/src/extensions/renderer/canvas/arrow-shapes.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/canvas/arrow-shapes"
  >;
}
declare module "cytoscape/src/extensions/renderer/canvas/drawing-edges.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/canvas/drawing-edges"
  >;
}
declare module "cytoscape/src/extensions/renderer/canvas/drawing-elements.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/canvas/drawing-elements"
  >;
}
declare module "cytoscape/src/extensions/renderer/canvas/drawing-images.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/canvas/drawing-images"
  >;
}
declare module "cytoscape/src/extensions/renderer/canvas/drawing-label-text.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/canvas/drawing-label-text"
  >;
}
declare module "cytoscape/src/extensions/renderer/canvas/drawing-nodes.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/canvas/drawing-nodes"
  >;
}
declare module "cytoscape/src/extensions/renderer/canvas/drawing-redraw.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/canvas/drawing-redraw"
  >;
}
declare module "cytoscape/src/extensions/renderer/canvas/drawing-shapes.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/canvas/drawing-shapes"
  >;
}
declare module "cytoscape/src/extensions/renderer/canvas/ele-texture-cache.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/canvas/ele-texture-cache"
  >;
}
declare module "cytoscape/src/extensions/renderer/canvas/export-image.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/canvas/export-image"
  >;
}
declare module "cytoscape/src/extensions/renderer/canvas/index.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/canvas/index"
  >;
}
declare module "cytoscape/src/extensions/renderer/canvas/layered-texture-cache.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/canvas/layered-texture-cache"
  >;
}
declare module "cytoscape/src/extensions/renderer/canvas/node-shapes.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/canvas/node-shapes"
  >;
}
declare module "cytoscape/src/extensions/renderer/canvas/texture-cache-defs.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/canvas/texture-cache-defs"
  >;
}
declare module "cytoscape/src/extensions/renderer/index.js" {
  declare module.exports: $Exports<"cytoscape/src/extensions/renderer/index">;
}
declare module "cytoscape/src/extensions/renderer/null/index.js" {
  declare module.exports: $Exports<
    "cytoscape/src/extensions/renderer/null/index"
  >;
}
declare module "cytoscape/src/heap.js" {
  declare module.exports: $Exports<"cytoscape/src/heap">;
}
declare module "cytoscape/src/index.js" {
  declare module.exports: $Exports<"cytoscape/src/index">;
}
declare module "cytoscape/src/is.js" {
  declare module.exports: $Exports<"cytoscape/src/is">;
}
declare module "cytoscape/src/map.js" {
  declare module.exports: $Exports<"cytoscape/src/map">;
}
declare module "cytoscape/src/math.js" {
  declare module.exports: $Exports<"cytoscape/src/math">;
}
declare module "cytoscape/src/promise.js" {
  declare module.exports: $Exports<"cytoscape/src/promise">;
}
declare module "cytoscape/src/selector.js" {
  declare module.exports: $Exports<"cytoscape/src/selector">;
}
declare module "cytoscape/src/set.js" {
  declare module.exports: $Exports<"cytoscape/src/set">;
}
declare module "cytoscape/src/style/apply.js" {
  declare module.exports: $Exports<"cytoscape/src/style/apply">;
}
declare module "cytoscape/src/style/bypass.js" {
  declare module.exports: $Exports<"cytoscape/src/style/bypass">;
}
declare module "cytoscape/src/style/container.js" {
  declare module.exports: $Exports<"cytoscape/src/style/container">;
}
declare module "cytoscape/src/style/get-for-ele.js" {
  declare module.exports: $Exports<"cytoscape/src/style/get-for-ele">;
}
declare module "cytoscape/src/style/index.js" {
  declare module.exports: $Exports<"cytoscape/src/style/index">;
}
declare module "cytoscape/src/style/json.js" {
  declare module.exports: $Exports<"cytoscape/src/style/json">;
}
declare module "cytoscape/src/style/parse.js" {
  declare module.exports: $Exports<"cytoscape/src/style/parse">;
}
declare module "cytoscape/src/style/properties.js" {
  declare module.exports: $Exports<"cytoscape/src/style/properties">;
}
declare module "cytoscape/src/style/string-sheet.js" {
  declare module.exports: $Exports<"cytoscape/src/style/string-sheet">;
}
declare module "cytoscape/src/stylesheet.js" {
  declare module.exports: $Exports<"cytoscape/src/stylesheet">;
}
declare module "cytoscape/src/util/colors.js" {
  declare module.exports: $Exports<"cytoscape/src/util/colors">;
}
declare module "cytoscape/src/util/index.js" {
  declare module.exports: $Exports<"cytoscape/src/util/index">;
}
declare module "cytoscape/src/util/maps.js" {
  declare module.exports: $Exports<"cytoscape/src/util/maps">;
}
declare module "cytoscape/src/util/memoize.js" {
  declare module.exports: $Exports<"cytoscape/src/util/memoize">;
}
declare module "cytoscape/src/util/regex.js" {
  declare module.exports: $Exports<"cytoscape/src/util/regex">;
}
declare module "cytoscape/src/util/sort.js" {
  declare module.exports: $Exports<"cytoscape/src/util/sort">;
}
declare module "cytoscape/src/util/strings.js" {
  declare module.exports: $Exports<"cytoscape/src/util/strings">;
}
declare module "cytoscape/src/util/timing.js" {
  declare module.exports: $Exports<"cytoscape/src/util/timing">;
}
declare module "cytoscape/src/version.js" {
  declare module.exports: $Exports<"cytoscape/src/version">;
}
declare module "cytoscape/src/window.js" {
  declare module.exports: $Exports<"cytoscape/src/window">;
}
