// flow-typed signature: 5777541658c929a9051674d09de7c997
// flow-typed version: <<STUB>>/cz-customizable-ghooks_v^1.5.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cz-customizable-ghooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "cz-customizable-ghooks" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "cz-customizable-ghooks/lib/index" {
  declare module.exports: any;
}

// Filename aliases
declare module "cz-customizable-ghooks/lib/index.js" {
  declare module.exports: $Exports<"cz-customizable-ghooks/lib/index">;
}
