// flow-typed signature: 63c1bc3a5a5279d0080a9203348bf533
// flow-typed version: <<STUB>>/docsify_v^4.1.14/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'docsify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "docsify" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "docsify/lib/docsify" {
  declare module.exports: any;
}

declare module "docsify/lib/docsify.min" {
  declare module.exports: any;
}

declare module "docsify/lib/plugins/emoji" {
  declare module.exports: any;
}

declare module "docsify/lib/plugins/emoji.min" {
  declare module.exports: any;
}

declare module "docsify/lib/plugins/external-script" {
  declare module.exports: any;
}

declare module "docsify/lib/plugins/external-script.min" {
  declare module.exports: any;
}

declare module "docsify/lib/plugins/front-matter" {
  declare module.exports: any;
}

declare module "docsify/lib/plugins/front-matter.min" {
  declare module.exports: any;
}

declare module "docsify/lib/plugins/ga" {
  declare module.exports: any;
}

declare module "docsify/lib/plugins/ga.min" {
  declare module.exports: any;
}

declare module "docsify/lib/plugins/search" {
  declare module.exports: any;
}

declare module "docsify/lib/plugins/search.min" {
  declare module.exports: any;
}

declare module "docsify/lib/plugins/zoom-image" {
  declare module.exports: any;
}

declare module "docsify/lib/plugins/zoom-image.min" {
  declare module.exports: any;
}

declare module "docsify/src/core/config" {
  declare module.exports: any;
}

declare module "docsify/src/core/event/index" {
  declare module.exports: any;
}

declare module "docsify/src/core/event/scroll" {
  declare module.exports: any;
}

declare module "docsify/src/core/event/sidebar" {
  declare module.exports: any;
}

declare module "docsify/src/core/fetch/ajax" {
  declare module.exports: any;
}

declare module "docsify/src/core/fetch/index" {
  declare module.exports: any;
}

declare module "docsify/src/core/global-api" {
  declare module.exports: any;
}

declare module "docsify/src/core/index" {
  declare module.exports: any;
}

declare module "docsify/src/core/init/index" {
  declare module.exports: any;
}

declare module "docsify/src/core/init/lifecycle" {
  declare module.exports: any;
}

declare module "docsify/src/core/render/compiler" {
  declare module.exports: any;
}

declare module "docsify/src/core/render/emojify" {
  declare module.exports: any;
}

declare module "docsify/src/core/render/gen-tree" {
  declare module.exports: any;
}

declare module "docsify/src/core/render/index" {
  declare module.exports: any;
}

declare module "docsify/src/core/render/progressbar" {
  declare module.exports: any;
}

declare module "docsify/src/core/render/slugify" {
  declare module.exports: any;
}

declare module "docsify/src/core/render/tpl" {
  declare module.exports: any;
}

declare module "docsify/src/core/router/history/abstract" {
  declare module.exports: any;
}

declare module "docsify/src/core/router/history/base" {
  declare module.exports: any;
}

declare module "docsify/src/core/router/history/hash" {
  declare module.exports: any;
}

declare module "docsify/src/core/router/history/html5" {
  declare module.exports: any;
}

declare module "docsify/src/core/router/index" {
  declare module.exports: any;
}

declare module "docsify/src/core/router/util" {
  declare module.exports: any;
}

declare module "docsify/src/core/util/core" {
  declare module.exports: any;
}

declare module "docsify/src/core/util/dom" {
  declare module.exports: any;
}

declare module "docsify/src/core/util/env" {
  declare module.exports: any;
}

declare module "docsify/src/core/util/index" {
  declare module.exports: any;
}

declare module "docsify/src/core/util/polyfill/css-vars" {
  declare module.exports: any;
}

declare module "docsify/src/plugins/emoji" {
  declare module.exports: any;
}

declare module "docsify/src/plugins/external-script" {
  declare module.exports: any;
}

declare module "docsify/src/plugins/front-matter/index" {
  declare module.exports: any;
}

declare module "docsify/src/plugins/front-matter/parser" {
  declare module.exports: any;
}

declare module "docsify/src/plugins/front-matter/yaml" {
  declare module.exports: any;
}

declare module "docsify/src/plugins/ga" {
  declare module.exports: any;
}

declare module "docsify/src/plugins/search/component" {
  declare module.exports: any;
}

declare module "docsify/src/plugins/search/index" {
  declare module.exports: any;
}

declare module "docsify/src/plugins/search/search" {
  declare module.exports: any;
}

declare module "docsify/src/plugins/zoom-image" {
  declare module.exports: any;
}

// Filename aliases
declare module "docsify/lib/docsify.js" {
  declare module.exports: $Exports<"docsify/lib/docsify">;
}
declare module "docsify/lib/docsify.min.js" {
  declare module.exports: $Exports<"docsify/lib/docsify.min">;
}
declare module "docsify/lib/plugins/emoji.js" {
  declare module.exports: $Exports<"docsify/lib/plugins/emoji">;
}
declare module "docsify/lib/plugins/emoji.min.js" {
  declare module.exports: $Exports<"docsify/lib/plugins/emoji.min">;
}
declare module "docsify/lib/plugins/external-script.js" {
  declare module.exports: $Exports<"docsify/lib/plugins/external-script">;
}
declare module "docsify/lib/plugins/external-script.min.js" {
  declare module.exports: $Exports<"docsify/lib/plugins/external-script.min">;
}
declare module "docsify/lib/plugins/front-matter.js" {
  declare module.exports: $Exports<"docsify/lib/plugins/front-matter">;
}
declare module "docsify/lib/plugins/front-matter.min.js" {
  declare module.exports: $Exports<"docsify/lib/plugins/front-matter.min">;
}
declare module "docsify/lib/plugins/ga.js" {
  declare module.exports: $Exports<"docsify/lib/plugins/ga">;
}
declare module "docsify/lib/plugins/ga.min.js" {
  declare module.exports: $Exports<"docsify/lib/plugins/ga.min">;
}
declare module "docsify/lib/plugins/search.js" {
  declare module.exports: $Exports<"docsify/lib/plugins/search">;
}
declare module "docsify/lib/plugins/search.min.js" {
  declare module.exports: $Exports<"docsify/lib/plugins/search.min">;
}
declare module "docsify/lib/plugins/zoom-image.js" {
  declare module.exports: $Exports<"docsify/lib/plugins/zoom-image">;
}
declare module "docsify/lib/plugins/zoom-image.min.js" {
  declare module.exports: $Exports<"docsify/lib/plugins/zoom-image.min">;
}
declare module "docsify/src/core/config.js" {
  declare module.exports: $Exports<"docsify/src/core/config">;
}
declare module "docsify/src/core/event/index.js" {
  declare module.exports: $Exports<"docsify/src/core/event/index">;
}
declare module "docsify/src/core/event/scroll.js" {
  declare module.exports: $Exports<"docsify/src/core/event/scroll">;
}
declare module "docsify/src/core/event/sidebar.js" {
  declare module.exports: $Exports<"docsify/src/core/event/sidebar">;
}
declare module "docsify/src/core/fetch/ajax.js" {
  declare module.exports: $Exports<"docsify/src/core/fetch/ajax">;
}
declare module "docsify/src/core/fetch/index.js" {
  declare module.exports: $Exports<"docsify/src/core/fetch/index">;
}
declare module "docsify/src/core/global-api.js" {
  declare module.exports: $Exports<"docsify/src/core/global-api">;
}
declare module "docsify/src/core/index.js" {
  declare module.exports: $Exports<"docsify/src/core/index">;
}
declare module "docsify/src/core/init/index.js" {
  declare module.exports: $Exports<"docsify/src/core/init/index">;
}
declare module "docsify/src/core/init/lifecycle.js" {
  declare module.exports: $Exports<"docsify/src/core/init/lifecycle">;
}
declare module "docsify/src/core/render/compiler.js" {
  declare module.exports: $Exports<"docsify/src/core/render/compiler">;
}
declare module "docsify/src/core/render/emojify.js" {
  declare module.exports: $Exports<"docsify/src/core/render/emojify">;
}
declare module "docsify/src/core/render/gen-tree.js" {
  declare module.exports: $Exports<"docsify/src/core/render/gen-tree">;
}
declare module "docsify/src/core/render/index.js" {
  declare module.exports: $Exports<"docsify/src/core/render/index">;
}
declare module "docsify/src/core/render/progressbar.js" {
  declare module.exports: $Exports<"docsify/src/core/render/progressbar">;
}
declare module "docsify/src/core/render/slugify.js" {
  declare module.exports: $Exports<"docsify/src/core/render/slugify">;
}
declare module "docsify/src/core/render/tpl.js" {
  declare module.exports: $Exports<"docsify/src/core/render/tpl">;
}
declare module "docsify/src/core/router/history/abstract.js" {
  declare module.exports: $Exports<"docsify/src/core/router/history/abstract">;
}
declare module "docsify/src/core/router/history/base.js" {
  declare module.exports: $Exports<"docsify/src/core/router/history/base">;
}
declare module "docsify/src/core/router/history/hash.js" {
  declare module.exports: $Exports<"docsify/src/core/router/history/hash">;
}
declare module "docsify/src/core/router/history/html5.js" {
  declare module.exports: $Exports<"docsify/src/core/router/history/html5">;
}
declare module "docsify/src/core/router/index.js" {
  declare module.exports: $Exports<"docsify/src/core/router/index">;
}
declare module "docsify/src/core/router/util.js" {
  declare module.exports: $Exports<"docsify/src/core/router/util">;
}
declare module "docsify/src/core/util/core.js" {
  declare module.exports: $Exports<"docsify/src/core/util/core">;
}
declare module "docsify/src/core/util/dom.js" {
  declare module.exports: $Exports<"docsify/src/core/util/dom">;
}
declare module "docsify/src/core/util/env.js" {
  declare module.exports: $Exports<"docsify/src/core/util/env">;
}
declare module "docsify/src/core/util/index.js" {
  declare module.exports: $Exports<"docsify/src/core/util/index">;
}
declare module "docsify/src/core/util/polyfill/css-vars.js" {
  declare module.exports: $Exports<"docsify/src/core/util/polyfill/css-vars">;
}
declare module "docsify/src/plugins/emoji.js" {
  declare module.exports: $Exports<"docsify/src/plugins/emoji">;
}
declare module "docsify/src/plugins/external-script.js" {
  declare module.exports: $Exports<"docsify/src/plugins/external-script">;
}
declare module "docsify/src/plugins/front-matter/index.js" {
  declare module.exports: $Exports<"docsify/src/plugins/front-matter/index">;
}
declare module "docsify/src/plugins/front-matter/parser.js" {
  declare module.exports: $Exports<"docsify/src/plugins/front-matter/parser">;
}
declare module "docsify/src/plugins/front-matter/yaml.js" {
  declare module.exports: $Exports<"docsify/src/plugins/front-matter/yaml">;
}
declare module "docsify/src/plugins/ga.js" {
  declare module.exports: $Exports<"docsify/src/plugins/ga">;
}
declare module "docsify/src/plugins/search/component.js" {
  declare module.exports: $Exports<"docsify/src/plugins/search/component">;
}
declare module "docsify/src/plugins/search/index.js" {
  declare module.exports: $Exports<"docsify/src/plugins/search/index">;
}
declare module "docsify/src/plugins/search/search.js" {
  declare module.exports: $Exports<"docsify/src/plugins/search/search">;
}
declare module "docsify/src/plugins/zoom-image.js" {
  declare module.exports: $Exports<"docsify/src/plugins/zoom-image">;
}
