// flow-typed signature: 993e14e00dc1d4ba352bc69687da596a
// flow-typed version: <<STUB>>/function-tree_v^0.4.7/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'function-tree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "function-tree" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "function-tree/demos/mobx/components/AddAssignment/index" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/components/App/index" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/components/Assignments/index" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/compositions/getMissingUsers" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/events/addAssignmentClicked" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/events/appMounted" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/events/newAssigmentAssigneAdded" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/events/newAssignmentAssigneeChanged" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/events/newAssignmentTitleChanged" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/factories/copyInputToData" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/factories/copyInputToView" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/factories/hasInputValue" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/factories/httpGet" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/factories/setView" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/functions/addAssignee" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/functions/addNewAssignment" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/functions/getMissingUsers" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/functions/postAssignment" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/functions/searchAssignee" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/functions/updateAssignmentId" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/main" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/models/Assignment" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/models/User" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/run" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/store" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/stores/DataStore" {
  declare module.exports: any;
}

declare module "function-tree/demos/mobx/stores/ViewStore" {
  declare module.exports: any;
}

declare module "function-tree/demos/node/functions/getCerebralMembers" {
  declare module.exports: any;
}

declare module "function-tree/demos/node/functions/takeAvatars" {
  declare module.exports: any;
}

declare module "function-tree/demos/node/functions/writeAvatars" {
  declare module.exports: any;
}

declare module "function-tree/demos/node/main" {
  declare module.exports: any;
}

declare module "function-tree/demos/node/runTask" {
  declare module.exports: any;
}

declare module "function-tree/demos/redux/components/AddAssignment/index" {
  declare module.exports: any;
}

declare module "function-tree/demos/redux/components/App/index" {
  declare module.exports: any;
}

declare module "function-tree/demos/redux/components/Assignments/index" {
  declare module.exports: any;
}

declare module "function-tree/demos/redux/compositions/getMissingUsers" {
  declare module.exports: any;
}

declare module "function-tree/demos/redux/constants" {
  declare module.exports: any;
}

declare module "function-tree/demos/redux/events/addAssignmentClicked" {
  declare module.exports: any;
}

declare module "function-tree/demos/redux/events/appMounted" {
  declare module.exports: any;
}

declare module "function-tree/demos/redux/events/newAssigmentAssigneAdded" {
  declare module.exports: any;
}

declare module "function-tree/demos/redux/events/newAssignmentAssigneeChanged" {
  declare module.exports: any;
}

declare module "function-tree/demos/redux/events/newAssignmentTitleChanged" {
  declare module.exports: any;
}

declare module "function-tree/demos/redux/factories/dispatch" {
  declare module.exports: any;
}

declare module "function-tree/demos/redux/factories/hasInputValue" {
  declare module.exports: any;
}

declare module "function-tree/demos/redux/factories/httpGet" {
  declare module.exports: any;
}

declare module "function-tree/demos/redux/functions/getMissingUsers" {
  declare module.exports: any;
}

declare module "function-tree/demos/redux/functions/hasAssignee" {
  declare module.exports: any;
}

declare module "function-tree/demos/redux/functions/postAssignment" {
  declare module.exports: any;
}

declare module "function-tree/demos/redux/functions/searchAssignee" {
  declare module.exports: any;
}

declare module "function-tree/demos/redux/main" {
  declare module.exports: any;
}

declare module "function-tree/demos/redux/reducer" {
  declare module.exports: any;
}

declare module "function-tree/demos/redux/run" {
  declare module.exports: any;
}

declare module "function-tree/demos/redux/store" {
  declare module.exports: any;
}

declare module "function-tree/demos/server" {
  declare module.exports: any;
}

declare module "function-tree/factories/debounce" {
  declare module.exports: any;
}

declare module "function-tree/providers/Context" {
  declare module.exports: any;
}

declare module "function-tree/providers/Debugger" {
  declare module.exports: any;
}

declare module "function-tree/providers/Execution" {
  declare module.exports: any;
}

declare module "function-tree/providers/Input" {
  declare module.exports: any;
}

declare module "function-tree/providers/NodeDebugger" {
  declare module.exports: any;
}

declare module "function-tree/providers/Path" {
  declare module.exports: any;
}

declare module "function-tree/providers/Redux" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/providers/Dashboard" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/providers/Firebase" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/runTask" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/common/actions/getChallenge" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/common/actions/getHousehold" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/common/actions/getProfile" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/common/actions/getProfileEmail" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/common/actions/rejectTask" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/common/actions/resolveTask" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/common/factories/hasInput" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/common/factories/log" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/common/helpers/calculateCurrentChallengePoints" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/common/helpers/sortByTotalCo2" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/create_household/actions/createHousehold" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/create_household/actions/setHousehold" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/create_household/actions/updateProfile" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/create_household/index" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/create_post_comment/actions/createPostComment" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/create_post_comment/actions/pushPostComment" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/create_post_comment/index" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/create_post/actions/createPost" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/create_post/actions/pushPost" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/create_post/index" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/create_profile/actions/createProfile" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/create_profile/actions/setProfile" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/create_profile/index" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/invite_to_household/actions/addNotification" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/invite_to_household/actions/createNotificationJoinHousehold" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/invite_to_household/actions/verifyUserIsAdmin" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/invite_to_household/index" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/join_challenge/actions/addChallengeParticipant" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/join_challenge/actions/checkParticipantExists" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/join_challenge/actions/getChallenge" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/join_challenge/actions/getDepartmentKey" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/join_challenge/actions/getHouseholdKey" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/join_challenge/actions/incrementChallengeParticipants" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/join_challenge/index" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/reply_household_invitation/actions/getNotification" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/reply_household_invitation/actions/updateHouseholdMembersAndCompanies" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/reply_household_invitation/actions/updateProfileHousehold" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/reply_household_invitation/index" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/actions/outputSelectedActivity" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/actions/updateChallengeDayScores" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/actions/updateChallengeDepartmentAllLeaderboard" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/actions/updateChallengeDepartmentEmployeesLeaderboard" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/actions/updateChallengeTotalScores" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/actions/updateHouseholdScores" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/actions/updateProfilesScores" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/chains/toggleLoggedActivity" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/activityExists" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/activityKeysToObject" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/addActivity" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/createNewLeaderboardHousehold" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/existingActivitySubCategoryScoresSubtraction" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/getScoreModifier" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/removeActivity" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/updateActivitiesCount" {
  declare module.exports: any;
}

declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/index" {
  declare module.exports: any;
}

declare module "function-tree/src/Abort" {
  declare module.exports: any;
}

declare module "function-tree/src/executeTree" {
  declare module.exports: any;
}

declare module "function-tree/src/index" {
  declare module.exports: any;
}

declare module "function-tree/src/Path" {
  declare module.exports: any;
}

declare module "function-tree/src/staticTree" {
  declare module.exports: any;
}

declare module "function-tree/tests/contextProvider" {
  declare module.exports: any;
}

declare module "function-tree/tests/executionProvider" {
  declare module.exports: any;
}

declare module "function-tree/tests/FunctionTree" {
  declare module.exports: any;
}

declare module "function-tree/tests/inputProvider" {
  declare module.exports: any;
}

declare module "function-tree/tests/nodeDebuggerProvider" {
  declare module.exports: any;
}

declare module "function-tree/tests/pathProvider" {
  declare module.exports: any;
}

// Filename aliases
declare module "function-tree/demos/mobx/components/AddAssignment/index.js" {
  declare module.exports: $Exports<
    "function-tree/demos/mobx/components/AddAssignment/index"
  >;
}
declare module "function-tree/demos/mobx/components/App/index.js" {
  declare module.exports: $Exports<
    "function-tree/demos/mobx/components/App/index"
  >;
}
declare module "function-tree/demos/mobx/components/Assignments/index.js" {
  declare module.exports: $Exports<
    "function-tree/demos/mobx/components/Assignments/index"
  >;
}
declare module "function-tree/demos/mobx/compositions/getMissingUsers.js" {
  declare module.exports: $Exports<
    "function-tree/demos/mobx/compositions/getMissingUsers"
  >;
}
declare module "function-tree/demos/mobx/events/addAssignmentClicked.js" {
  declare module.exports: $Exports<
    "function-tree/demos/mobx/events/addAssignmentClicked"
  >;
}
declare module "function-tree/demos/mobx/events/appMounted.js" {
  declare module.exports: $Exports<
    "function-tree/demos/mobx/events/appMounted"
  >;
}
declare module "function-tree/demos/mobx/events/newAssigmentAssigneAdded.js" {
  declare module.exports: $Exports<
    "function-tree/demos/mobx/events/newAssigmentAssigneAdded"
  >;
}
declare module "function-tree/demos/mobx/events/newAssignmentAssigneeChanged.js" {
  declare module.exports: $Exports<
    "function-tree/demos/mobx/events/newAssignmentAssigneeChanged"
  >;
}
declare module "function-tree/demos/mobx/events/newAssignmentTitleChanged.js" {
  declare module.exports: $Exports<
    "function-tree/demos/mobx/events/newAssignmentTitleChanged"
  >;
}
declare module "function-tree/demos/mobx/factories/copyInputToData.js" {
  declare module.exports: $Exports<
    "function-tree/demos/mobx/factories/copyInputToData"
  >;
}
declare module "function-tree/demos/mobx/factories/copyInputToView.js" {
  declare module.exports: $Exports<
    "function-tree/demos/mobx/factories/copyInputToView"
  >;
}
declare module "function-tree/demos/mobx/factories/hasInputValue.js" {
  declare module.exports: $Exports<
    "function-tree/demos/mobx/factories/hasInputValue"
  >;
}
declare module "function-tree/demos/mobx/factories/httpGet.js" {
  declare module.exports: $Exports<
    "function-tree/demos/mobx/factories/httpGet"
  >;
}
declare module "function-tree/demos/mobx/factories/setView.js" {
  declare module.exports: $Exports<
    "function-tree/demos/mobx/factories/setView"
  >;
}
declare module "function-tree/demos/mobx/functions/addAssignee.js" {
  declare module.exports: $Exports<
    "function-tree/demos/mobx/functions/addAssignee"
  >;
}
declare module "function-tree/demos/mobx/functions/addNewAssignment.js" {
  declare module.exports: $Exports<
    "function-tree/demos/mobx/functions/addNewAssignment"
  >;
}
declare module "function-tree/demos/mobx/functions/getMissingUsers.js" {
  declare module.exports: $Exports<
    "function-tree/demos/mobx/functions/getMissingUsers"
  >;
}
declare module "function-tree/demos/mobx/functions/postAssignment.js" {
  declare module.exports: $Exports<
    "function-tree/demos/mobx/functions/postAssignment"
  >;
}
declare module "function-tree/demos/mobx/functions/searchAssignee.js" {
  declare module.exports: $Exports<
    "function-tree/demos/mobx/functions/searchAssignee"
  >;
}
declare module "function-tree/demos/mobx/functions/updateAssignmentId.js" {
  declare module.exports: $Exports<
    "function-tree/demos/mobx/functions/updateAssignmentId"
  >;
}
declare module "function-tree/demos/mobx/main.js" {
  declare module.exports: $Exports<"function-tree/demos/mobx/main">;
}
declare module "function-tree/demos/mobx/models/Assignment.js" {
  declare module.exports: $Exports<
    "function-tree/demos/mobx/models/Assignment"
  >;
}
declare module "function-tree/demos/mobx/models/User.js" {
  declare module.exports: $Exports<"function-tree/demos/mobx/models/User">;
}
declare module "function-tree/demos/mobx/run.js" {
  declare module.exports: $Exports<"function-tree/demos/mobx/run">;
}
declare module "function-tree/demos/mobx/store.js" {
  declare module.exports: $Exports<"function-tree/demos/mobx/store">;
}
declare module "function-tree/demos/mobx/stores/DataStore.js" {
  declare module.exports: $Exports<"function-tree/demos/mobx/stores/DataStore">;
}
declare module "function-tree/demos/mobx/stores/ViewStore.js" {
  declare module.exports: $Exports<"function-tree/demos/mobx/stores/ViewStore">;
}
declare module "function-tree/demos/node/functions/getCerebralMembers.js" {
  declare module.exports: $Exports<
    "function-tree/demos/node/functions/getCerebralMembers"
  >;
}
declare module "function-tree/demos/node/functions/takeAvatars.js" {
  declare module.exports: $Exports<
    "function-tree/demos/node/functions/takeAvatars"
  >;
}
declare module "function-tree/demos/node/functions/writeAvatars.js" {
  declare module.exports: $Exports<
    "function-tree/demos/node/functions/writeAvatars"
  >;
}
declare module "function-tree/demos/node/main.js" {
  declare module.exports: $Exports<"function-tree/demos/node/main">;
}
declare module "function-tree/demos/node/runTask.js" {
  declare module.exports: $Exports<"function-tree/demos/node/runTask">;
}
declare module "function-tree/demos/redux/components/AddAssignment/index.js" {
  declare module.exports: $Exports<
    "function-tree/demos/redux/components/AddAssignment/index"
  >;
}
declare module "function-tree/demos/redux/components/App/index.js" {
  declare module.exports: $Exports<
    "function-tree/demos/redux/components/App/index"
  >;
}
declare module "function-tree/demos/redux/components/Assignments/index.js" {
  declare module.exports: $Exports<
    "function-tree/demos/redux/components/Assignments/index"
  >;
}
declare module "function-tree/demos/redux/compositions/getMissingUsers.js" {
  declare module.exports: $Exports<
    "function-tree/demos/redux/compositions/getMissingUsers"
  >;
}
declare module "function-tree/demos/redux/constants.js" {
  declare module.exports: $Exports<"function-tree/demos/redux/constants">;
}
declare module "function-tree/demos/redux/events/addAssignmentClicked.js" {
  declare module.exports: $Exports<
    "function-tree/demos/redux/events/addAssignmentClicked"
  >;
}
declare module "function-tree/demos/redux/events/appMounted.js" {
  declare module.exports: $Exports<
    "function-tree/demos/redux/events/appMounted"
  >;
}
declare module "function-tree/demos/redux/events/newAssigmentAssigneAdded.js" {
  declare module.exports: $Exports<
    "function-tree/demos/redux/events/newAssigmentAssigneAdded"
  >;
}
declare module "function-tree/demos/redux/events/newAssignmentAssigneeChanged.js" {
  declare module.exports: $Exports<
    "function-tree/demos/redux/events/newAssignmentAssigneeChanged"
  >;
}
declare module "function-tree/demos/redux/events/newAssignmentTitleChanged.js" {
  declare module.exports: $Exports<
    "function-tree/demos/redux/events/newAssignmentTitleChanged"
  >;
}
declare module "function-tree/demos/redux/factories/dispatch.js" {
  declare module.exports: $Exports<
    "function-tree/demos/redux/factories/dispatch"
  >;
}
declare module "function-tree/demos/redux/factories/hasInputValue.js" {
  declare module.exports: $Exports<
    "function-tree/demos/redux/factories/hasInputValue"
  >;
}
declare module "function-tree/demos/redux/factories/httpGet.js" {
  declare module.exports: $Exports<
    "function-tree/demos/redux/factories/httpGet"
  >;
}
declare module "function-tree/demos/redux/functions/getMissingUsers.js" {
  declare module.exports: $Exports<
    "function-tree/demos/redux/functions/getMissingUsers"
  >;
}
declare module "function-tree/demos/redux/functions/hasAssignee.js" {
  declare module.exports: $Exports<
    "function-tree/demos/redux/functions/hasAssignee"
  >;
}
declare module "function-tree/demos/redux/functions/postAssignment.js" {
  declare module.exports: $Exports<
    "function-tree/demos/redux/functions/postAssignment"
  >;
}
declare module "function-tree/demos/redux/functions/searchAssignee.js" {
  declare module.exports: $Exports<
    "function-tree/demos/redux/functions/searchAssignee"
  >;
}
declare module "function-tree/demos/redux/main.js" {
  declare module.exports: $Exports<"function-tree/demos/redux/main">;
}
declare module "function-tree/demos/redux/reducer.js" {
  declare module.exports: $Exports<"function-tree/demos/redux/reducer">;
}
declare module "function-tree/demos/redux/run.js" {
  declare module.exports: $Exports<"function-tree/demos/redux/run">;
}
declare module "function-tree/demos/redux/store.js" {
  declare module.exports: $Exports<"function-tree/demos/redux/store">;
}
declare module "function-tree/demos/server.js" {
  declare module.exports: $Exports<"function-tree/demos/server">;
}
declare module "function-tree/factories/debounce.js" {
  declare module.exports: $Exports<"function-tree/factories/debounce">;
}
declare module "function-tree/providers/Context.js" {
  declare module.exports: $Exports<"function-tree/providers/Context">;
}
declare module "function-tree/providers/Debugger.js" {
  declare module.exports: $Exports<"function-tree/providers/Debugger">;
}
declare module "function-tree/providers/Execution.js" {
  declare module.exports: $Exports<"function-tree/providers/Execution">;
}
declare module "function-tree/providers/Input.js" {
  declare module.exports: $Exports<"function-tree/providers/Input">;
}
declare module "function-tree/providers/NodeDebugger.js" {
  declare module.exports: $Exports<"function-tree/providers/NodeDebugger">;
}
declare module "function-tree/providers/Path.js" {
  declare module.exports: $Exports<"function-tree/providers/Path">;
}
declare module "function-tree/providers/Redux.js" {
  declare module.exports: $Exports<"function-tree/providers/Redux">;
}
declare module "function-tree/referenceApp/providers/Dashboard.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/providers/Dashboard"
  >;
}
declare module "function-tree/referenceApp/providers/Firebase.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/providers/Firebase"
  >;
}
declare module "function-tree/referenceApp/runTask.js" {
  declare module.exports: $Exports<"function-tree/referenceApp/runTask">;
}
declare module "function-tree/referenceApp/taskHandlers/common/actions/getChallenge.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/common/actions/getChallenge"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/common/actions/getHousehold.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/common/actions/getHousehold"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/common/actions/getProfile.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/common/actions/getProfile"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/common/actions/getProfileEmail.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/common/actions/getProfileEmail"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/common/actions/rejectTask.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/common/actions/rejectTask"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/common/actions/resolveTask.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/common/actions/resolveTask"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/common/factories/hasInput.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/common/factories/hasInput"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/common/factories/log.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/common/factories/log"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/common/helpers/calculateCurrentChallengePoints.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/common/helpers/calculateCurrentChallengePoints"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/common/helpers/sortByTotalCo2.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/common/helpers/sortByTotalCo2"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/create_household/actions/createHousehold.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/create_household/actions/createHousehold"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/create_household/actions/setHousehold.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/create_household/actions/setHousehold"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/create_household/actions/updateProfile.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/create_household/actions/updateProfile"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/create_household/index.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/create_household/index"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/create_post_comment/actions/createPostComment.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/create_post_comment/actions/createPostComment"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/create_post_comment/actions/pushPostComment.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/create_post_comment/actions/pushPostComment"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/create_post_comment/index.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/create_post_comment/index"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/create_post/actions/createPost.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/create_post/actions/createPost"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/create_post/actions/pushPost.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/create_post/actions/pushPost"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/create_post/index.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/create_post/index"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/create_profile/actions/createProfile.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/create_profile/actions/createProfile"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/create_profile/actions/setProfile.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/create_profile/actions/setProfile"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/create_profile/index.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/create_profile/index"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/invite_to_household/actions/addNotification.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/invite_to_household/actions/addNotification"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/invite_to_household/actions/createNotificationJoinHousehold.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/invite_to_household/actions/createNotificationJoinHousehold"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/invite_to_household/actions/verifyUserIsAdmin.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/invite_to_household/actions/verifyUserIsAdmin"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/invite_to_household/index.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/invite_to_household/index"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/join_challenge/actions/addChallengeParticipant.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/join_challenge/actions/addChallengeParticipant"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/join_challenge/actions/checkParticipantExists.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/join_challenge/actions/checkParticipantExists"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/join_challenge/actions/getChallenge.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/join_challenge/actions/getChallenge"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/join_challenge/actions/getDepartmentKey.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/join_challenge/actions/getDepartmentKey"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/join_challenge/actions/getHouseholdKey.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/join_challenge/actions/getHouseholdKey"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/join_challenge/actions/incrementChallengeParticipants.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/join_challenge/actions/incrementChallengeParticipants"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/join_challenge/index.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/join_challenge/index"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/reply_household_invitation/actions/getNotification.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/reply_household_invitation/actions/getNotification"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/reply_household_invitation/actions/updateHouseholdMembersAndCompanies.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/reply_household_invitation/actions/updateHouseholdMembersAndCompanies"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/reply_household_invitation/actions/updateProfileHousehold.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/reply_household_invitation/actions/updateProfileHousehold"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/reply_household_invitation/index.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/reply_household_invitation/index"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/actions/outputSelectedActivity.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/toggle_logged_activity/actions/outputSelectedActivity"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/actions/updateChallengeDayScores.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/toggle_logged_activity/actions/updateChallengeDayScores"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/actions/updateChallengeDepartmentAllLeaderboard.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/toggle_logged_activity/actions/updateChallengeDepartmentAllLeaderboard"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/actions/updateChallengeDepartmentEmployeesLeaderboard.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/toggle_logged_activity/actions/updateChallengeDepartmentEmployeesLeaderboard"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/actions/updateChallengeTotalScores.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/toggle_logged_activity/actions/updateChallengeTotalScores"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/actions/updateHouseholdScores.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/toggle_logged_activity/actions/updateHouseholdScores"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/actions/updateProfilesScores.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/toggle_logged_activity/actions/updateProfilesScores"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/chains/toggleLoggedActivity.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/toggle_logged_activity/chains/toggleLoggedActivity"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/activityExists.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/activityExists"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/activityKeysToObject.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/activityKeysToObject"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/addActivity.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/addActivity"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/createNewLeaderboardHousehold.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/createNewLeaderboardHousehold"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/existingActivitySubCategoryScoresSubtraction.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/existingActivitySubCategoryScoresSubtraction"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/getScoreModifier.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/getScoreModifier"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/removeActivity.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/removeActivity"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/updateActivitiesCount.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/toggle_logged_activity/helpers/updateActivitiesCount"
  >;
}
declare module "function-tree/referenceApp/taskHandlers/toggle_logged_activity/index.js" {
  declare module.exports: $Exports<
    "function-tree/referenceApp/taskHandlers/toggle_logged_activity/index"
  >;
}
declare module "function-tree/src/Abort.js" {
  declare module.exports: $Exports<"function-tree/src/Abort">;
}
declare module "function-tree/src/executeTree.js" {
  declare module.exports: $Exports<"function-tree/src/executeTree">;
}
declare module "function-tree/src/index.js" {
  declare module.exports: $Exports<"function-tree/src/index">;
}
declare module "function-tree/src/Path.js" {
  declare module.exports: $Exports<"function-tree/src/Path">;
}
declare module "function-tree/src/staticTree.js" {
  declare module.exports: $Exports<"function-tree/src/staticTree">;
}
declare module "function-tree/tests/contextProvider.js" {
  declare module.exports: $Exports<"function-tree/tests/contextProvider">;
}
declare module "function-tree/tests/executionProvider.js" {
  declare module.exports: $Exports<"function-tree/tests/executionProvider">;
}
declare module "function-tree/tests/FunctionTree.js" {
  declare module.exports: $Exports<"function-tree/tests/FunctionTree">;
}
declare module "function-tree/tests/inputProvider.js" {
  declare module.exports: $Exports<"function-tree/tests/inputProvider">;
}
declare module "function-tree/tests/nodeDebuggerProvider.js" {
  declare module.exports: $Exports<"function-tree/tests/nodeDebuggerProvider">;
}
declare module "function-tree/tests/pathProvider.js" {
  declare module.exports: $Exports<"function-tree/tests/pathProvider">;
}
