// flow-typed signature: ae4ead0438cc2bbda1b5fa2ea5d2ac40
// flow-typed version: <<STUB>>/grpc-web-client_v^0.2.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grpc-web-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "grpc-web-client" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "grpc-web-client/dist/ChunkParser" {
  declare module.exports: any;
}

declare module "grpc-web-client/dist/debug" {
  declare module.exports: any;
}

declare module "grpc-web-client/dist/grpc" {
  declare module.exports: any;
}

declare module "grpc-web-client/dist/index" {
  declare module.exports: any;
}

declare module "grpc-web-client/dist/transports/fetch" {
  declare module.exports: any;
}

declare module "grpc-web-client/dist/transports/msStream" {
  declare module.exports: any;
}

declare module "grpc-web-client/dist/transports/Transport" {
  declare module.exports: any;
}

declare module "grpc-web-client/dist/transports/xhr" {
  declare module.exports: any;
}

// Filename aliases
declare module "grpc-web-client/dist/ChunkParser.js" {
  declare module.exports: $Exports<"grpc-web-client/dist/ChunkParser">;
}
declare module "grpc-web-client/dist/debug.js" {
  declare module.exports: $Exports<"grpc-web-client/dist/debug">;
}
declare module "grpc-web-client/dist/grpc.js" {
  declare module.exports: $Exports<"grpc-web-client/dist/grpc">;
}
declare module "grpc-web-client/dist/index.js" {
  declare module.exports: $Exports<"grpc-web-client/dist/index">;
}
declare module "grpc-web-client/dist/transports/fetch.js" {
  declare module.exports: $Exports<"grpc-web-client/dist/transports/fetch">;
}
declare module "grpc-web-client/dist/transports/msStream.js" {
  declare module.exports: $Exports<"grpc-web-client/dist/transports/msStream">;
}
declare module "grpc-web-client/dist/transports/Transport.js" {
  declare module.exports: $Exports<"grpc-web-client/dist/transports/Transport">;
}
declare module "grpc-web-client/dist/transports/xhr.js" {
  declare module.exports: $Exports<"grpc-web-client/dist/transports/xhr">;
}
