// flow-typed signature: ef676a9c7e1db79d2e6e11753b08c451
// flow-typed version: <<STUB>>/q_v^1.5.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'q'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "q" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "q/q" {
  declare module.exports: any;
}

declare module "q/queue" {
  declare module.exports: any;
}

// Filename aliases
declare module "q/q.js" {
  declare module.exports: $Exports<"q/q">;
}
declare module "q/queue.js" {
  declare module.exports: $Exports<"q/queue">;
}
