// flow-typed signature: 9e0d16d764cb27041f324ac0ee2a434f
// flow-typed version: <<STUB>>/react-sigma_v^1.2.18/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sigma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-sigma" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-sigma/dist/react-sigma" {
  declare module.exports: any;
}

declare module "react-sigma/dist/react-sigma.min" {
  declare module.exports: any;
}

declare module "react-sigma/es/Dagre" {
  declare module.exports: any;
}

declare module "react-sigma/es/EdgeShapes" {
  declare module.exports: any;
}

declare module "react-sigma/es/Filter" {
  declare module.exports: any;
}

declare module "react-sigma/es/ForceAtlas2" {
  declare module.exports: any;
}

declare module "react-sigma/es/ForceLink" {
  declare module.exports: any;
}

declare module "react-sigma/es/index" {
  declare module.exports: any;
}

declare module "react-sigma/es/LoadGEXF" {
  declare module.exports: any;
}

declare module "react-sigma/es/LoadJSON" {
  declare module.exports: any;
}

declare module "react-sigma/es/NeoCypher" {
  declare module.exports: any;
}

declare module "react-sigma/es/NeoGraphItemsProducers" {
  declare module.exports: any;
}

declare module "react-sigma/es/NodeShapes" {
  declare module.exports: any;
}

declare module "react-sigma/es/NOverlap" {
  declare module.exports: any;
}

declare module "react-sigma/es/RandomizeNodePositions" {
  declare module.exports: any;
}

declare module "react-sigma/es/ReactSigmaLayoutPlugin" {
  declare module.exports: any;
}

declare module "react-sigma/es/RelativeSize" {
  declare module.exports: any;
}

declare module "react-sigma/es/Sigma" {
  declare module.exports: any;
}

declare module "react-sigma/es/SigmaEnableSVG" {
  declare module.exports: any;
}

declare module "react-sigma/es/SigmaEnableWebGL" {
  declare module.exports: any;
}

declare module "react-sigma/es/tools" {
  declare module.exports: any;
}

declare module "react-sigma/es/Utils" {
  declare module.exports: any;
}

declare module "react-sigma/lib/Dagre" {
  declare module.exports: any;
}

declare module "react-sigma/lib/EdgeShapes" {
  declare module.exports: any;
}

declare module "react-sigma/lib/Filter" {
  declare module.exports: any;
}

declare module "react-sigma/lib/ForceAtlas2" {
  declare module.exports: any;
}

declare module "react-sigma/lib/ForceLink" {
  declare module.exports: any;
}

declare module "react-sigma/lib/index" {
  declare module.exports: any;
}

declare module "react-sigma/lib/LoadGEXF" {
  declare module.exports: any;
}

declare module "react-sigma/lib/LoadJSON" {
  declare module.exports: any;
}

declare module "react-sigma/lib/NeoCypher" {
  declare module.exports: any;
}

declare module "react-sigma/lib/NeoGraphItemsProducers" {
  declare module.exports: any;
}

declare module "react-sigma/lib/NodeShapes" {
  declare module.exports: any;
}

declare module "react-sigma/lib/NOverlap" {
  declare module.exports: any;
}

declare module "react-sigma/lib/RandomizeNodePositions" {
  declare module.exports: any;
}

declare module "react-sigma/lib/ReactSigmaLayoutPlugin" {
  declare module.exports: any;
}

declare module "react-sigma/lib/RelativeSize" {
  declare module.exports: any;
}

declare module "react-sigma/lib/Sigma" {
  declare module.exports: any;
}

declare module "react-sigma/lib/SigmaEnableSVG" {
  declare module.exports: any;
}

declare module "react-sigma/lib/SigmaEnableWebGL" {
  declare module.exports: any;
}

declare module "react-sigma/lib/tools" {
  declare module.exports: any;
}

declare module "react-sigma/lib/Utils" {
  declare module.exports: any;
}

declare module "react-sigma/sigma/edges" {
  declare module.exports: any;
}

declare module "react-sigma/sigma/layout.dagre" {
  declare module.exports: any;
}

declare module "react-sigma/sigma/layout.forceAtlas2" {
  declare module.exports: any;
}

declare module "react-sigma/sigma/layout.forceLink" {
  declare module.exports: any;
}

declare module "react-sigma/sigma/layout.noverlap" {
  declare module.exports: any;
}

declare module "react-sigma/sigma/main" {
  declare module.exports: any;
}

declare module "react-sigma/sigma/neo4j.cypher" {
  declare module.exports: any;
}

declare module "react-sigma/sigma/nodes" {
  declare module.exports: any;
}

declare module "react-sigma/sigma/parsers.gexf" {
  declare module.exports: any;
}

declare module "react-sigma/sigma/parsers.json" {
  declare module.exports: any;
}

declare module "react-sigma/sigma/plugins.animate" {
  declare module.exports: any;
}

declare module "react-sigma/sigma/plugins.filter" {
  declare module.exports: any;
}

declare module "react-sigma/sigma/plugins.generators" {
  declare module.exports: any;
}

declare module "react-sigma/sigma/plugins.relativeSize" {
  declare module.exports: any;
}

declare module "react-sigma/sigma/sigma.plugins.dragNodes" {
  declare module.exports: any;
}

declare module "react-sigma/sigma/svg" {
  declare module.exports: any;
}

declare module "react-sigma/sigma/webgl" {
  declare module.exports: any;
}

// Filename aliases
declare module "react-sigma/dist/react-sigma.js" {
  declare module.exports: $Exports<"react-sigma/dist/react-sigma">;
}
declare module "react-sigma/dist/react-sigma.min.js" {
  declare module.exports: $Exports<"react-sigma/dist/react-sigma.min">;
}
declare module "react-sigma/es/Dagre.js" {
  declare module.exports: $Exports<"react-sigma/es/Dagre">;
}
declare module "react-sigma/es/EdgeShapes.js" {
  declare module.exports: $Exports<"react-sigma/es/EdgeShapes">;
}
declare module "react-sigma/es/Filter.js" {
  declare module.exports: $Exports<"react-sigma/es/Filter">;
}
declare module "react-sigma/es/ForceAtlas2.js" {
  declare module.exports: $Exports<"react-sigma/es/ForceAtlas2">;
}
declare module "react-sigma/es/ForceLink.js" {
  declare module.exports: $Exports<"react-sigma/es/ForceLink">;
}
declare module "react-sigma/es/index.js" {
  declare module.exports: $Exports<"react-sigma/es/index">;
}
declare module "react-sigma/es/LoadGEXF.js" {
  declare module.exports: $Exports<"react-sigma/es/LoadGEXF">;
}
declare module "react-sigma/es/LoadJSON.js" {
  declare module.exports: $Exports<"react-sigma/es/LoadJSON">;
}
declare module "react-sigma/es/NeoCypher.js" {
  declare module.exports: $Exports<"react-sigma/es/NeoCypher">;
}
declare module "react-sigma/es/NeoGraphItemsProducers.js" {
  declare module.exports: $Exports<"react-sigma/es/NeoGraphItemsProducers">;
}
declare module "react-sigma/es/NodeShapes.js" {
  declare module.exports: $Exports<"react-sigma/es/NodeShapes">;
}
declare module "react-sigma/es/NOverlap.js" {
  declare module.exports: $Exports<"react-sigma/es/NOverlap">;
}
declare module "react-sigma/es/RandomizeNodePositions.js" {
  declare module.exports: $Exports<"react-sigma/es/RandomizeNodePositions">;
}
declare module "react-sigma/es/ReactSigmaLayoutPlugin.js" {
  declare module.exports: $Exports<"react-sigma/es/ReactSigmaLayoutPlugin">;
}
declare module "react-sigma/es/RelativeSize.js" {
  declare module.exports: $Exports<"react-sigma/es/RelativeSize">;
}
declare module "react-sigma/es/Sigma.js" {
  declare module.exports: $Exports<"react-sigma/es/Sigma">;
}
declare module "react-sigma/es/SigmaEnableSVG.js" {
  declare module.exports: $Exports<"react-sigma/es/SigmaEnableSVG">;
}
declare module "react-sigma/es/SigmaEnableWebGL.js" {
  declare module.exports: $Exports<"react-sigma/es/SigmaEnableWebGL">;
}
declare module "react-sigma/es/tools.js" {
  declare module.exports: $Exports<"react-sigma/es/tools">;
}
declare module "react-sigma/es/Utils.js" {
  declare module.exports: $Exports<"react-sigma/es/Utils">;
}
declare module "react-sigma/lib/Dagre.js" {
  declare module.exports: $Exports<"react-sigma/lib/Dagre">;
}
declare module "react-sigma/lib/EdgeShapes.js" {
  declare module.exports: $Exports<"react-sigma/lib/EdgeShapes">;
}
declare module "react-sigma/lib/Filter.js" {
  declare module.exports: $Exports<"react-sigma/lib/Filter">;
}
declare module "react-sigma/lib/ForceAtlas2.js" {
  declare module.exports: $Exports<"react-sigma/lib/ForceAtlas2">;
}
declare module "react-sigma/lib/ForceLink.js" {
  declare module.exports: $Exports<"react-sigma/lib/ForceLink">;
}
declare module "react-sigma/lib/index.js" {
  declare module.exports: $Exports<"react-sigma/lib/index">;
}
declare module "react-sigma/lib/LoadGEXF.js" {
  declare module.exports: $Exports<"react-sigma/lib/LoadGEXF">;
}
declare module "react-sigma/lib/LoadJSON.js" {
  declare module.exports: $Exports<"react-sigma/lib/LoadJSON">;
}
declare module "react-sigma/lib/NeoCypher.js" {
  declare module.exports: $Exports<"react-sigma/lib/NeoCypher">;
}
declare module "react-sigma/lib/NeoGraphItemsProducers.js" {
  declare module.exports: $Exports<"react-sigma/lib/NeoGraphItemsProducers">;
}
declare module "react-sigma/lib/NodeShapes.js" {
  declare module.exports: $Exports<"react-sigma/lib/NodeShapes">;
}
declare module "react-sigma/lib/NOverlap.js" {
  declare module.exports: $Exports<"react-sigma/lib/NOverlap">;
}
declare module "react-sigma/lib/RandomizeNodePositions.js" {
  declare module.exports: $Exports<"react-sigma/lib/RandomizeNodePositions">;
}
declare module "react-sigma/lib/ReactSigmaLayoutPlugin.js" {
  declare module.exports: $Exports<"react-sigma/lib/ReactSigmaLayoutPlugin">;
}
declare module "react-sigma/lib/RelativeSize.js" {
  declare module.exports: $Exports<"react-sigma/lib/RelativeSize">;
}
declare module "react-sigma/lib/Sigma.js" {
  declare module.exports: $Exports<"react-sigma/lib/Sigma">;
}
declare module "react-sigma/lib/SigmaEnableSVG.js" {
  declare module.exports: $Exports<"react-sigma/lib/SigmaEnableSVG">;
}
declare module "react-sigma/lib/SigmaEnableWebGL.js" {
  declare module.exports: $Exports<"react-sigma/lib/SigmaEnableWebGL">;
}
declare module "react-sigma/lib/tools.js" {
  declare module.exports: $Exports<"react-sigma/lib/tools">;
}
declare module "react-sigma/lib/Utils.js" {
  declare module.exports: $Exports<"react-sigma/lib/Utils">;
}
declare module "react-sigma/sigma/edges.js" {
  declare module.exports: $Exports<"react-sigma/sigma/edges">;
}
declare module "react-sigma/sigma/layout.dagre.js" {
  declare module.exports: $Exports<"react-sigma/sigma/layout.dagre">;
}
declare module "react-sigma/sigma/layout.forceAtlas2.js" {
  declare module.exports: $Exports<"react-sigma/sigma/layout.forceAtlas2">;
}
declare module "react-sigma/sigma/layout.forceLink.js" {
  declare module.exports: $Exports<"react-sigma/sigma/layout.forceLink">;
}
declare module "react-sigma/sigma/layout.noverlap.js" {
  declare module.exports: $Exports<"react-sigma/sigma/layout.noverlap">;
}
declare module "react-sigma/sigma/main.js" {
  declare module.exports: $Exports<"react-sigma/sigma/main">;
}
declare module "react-sigma/sigma/neo4j.cypher.js" {
  declare module.exports: $Exports<"react-sigma/sigma/neo4j.cypher">;
}
declare module "react-sigma/sigma/nodes.js" {
  declare module.exports: $Exports<"react-sigma/sigma/nodes">;
}
declare module "react-sigma/sigma/parsers.gexf.js" {
  declare module.exports: $Exports<"react-sigma/sigma/parsers.gexf">;
}
declare module "react-sigma/sigma/parsers.json.js" {
  declare module.exports: $Exports<"react-sigma/sigma/parsers.json">;
}
declare module "react-sigma/sigma/plugins.animate.js" {
  declare module.exports: $Exports<"react-sigma/sigma/plugins.animate">;
}
declare module "react-sigma/sigma/plugins.filter.js" {
  declare module.exports: $Exports<"react-sigma/sigma/plugins.filter">;
}
declare module "react-sigma/sigma/plugins.generators.js" {
  declare module.exports: $Exports<"react-sigma/sigma/plugins.generators">;
}
declare module "react-sigma/sigma/plugins.relativeSize.js" {
  declare module.exports: $Exports<"react-sigma/sigma/plugins.relativeSize">;
}
declare module "react-sigma/sigma/sigma.plugins.dragNodes.js" {
  declare module.exports: $Exports<"react-sigma/sigma/sigma.plugins.dragNodes">;
}
declare module "react-sigma/sigma/svg.js" {
  declare module.exports: $Exports<"react-sigma/sigma/svg">;
}
declare module "react-sigma/sigma/webgl.js" {
  declare module.exports: $Exports<"react-sigma/sigma/webgl">;
}
