// flow-typed signature: ab2dd3426ddb07f71f4c9c70bd4d39e4
// flow-typed version: <<STUB>>/react-placeholder_v^1.0.4/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-placeholder'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-placeholder" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-placeholder/lib/index" {
  declare module.exports: any;
}

declare module "react-placeholder/lib/placeholders/index" {
  declare module.exports: any;
}

declare module "react-placeholder/lib/placeholders/MediaBlock" {
  declare module.exports: any;
}

declare module "react-placeholder/lib/placeholders/RectShape" {
  declare module.exports: any;
}

declare module "react-placeholder/lib/placeholders/RoundShape" {
  declare module.exports: any;
}

declare module "react-placeholder/lib/placeholders/TextBlock" {
  declare module.exports: any;
}

declare module "react-placeholder/lib/placeholders/TextRow" {
  declare module.exports: any;
}

declare module "react-placeholder/lib/ReactPlaceholder" {
  declare module.exports: any;
}

// Filename aliases
declare module "react-placeholder/lib/index.js" {
  declare module.exports: $Exports<"react-placeholder/lib/index">;
}
declare module "react-placeholder/lib/placeholders/index.js" {
  declare module.exports: $Exports<"react-placeholder/lib/placeholders/index">;
}
declare module "react-placeholder/lib/placeholders/MediaBlock.js" {
  declare module.exports: $Exports<
    "react-placeholder/lib/placeholders/MediaBlock"
  >;
}
declare module "react-placeholder/lib/placeholders/RectShape.js" {
  declare module.exports: $Exports<
    "react-placeholder/lib/placeholders/RectShape"
  >;
}
declare module "react-placeholder/lib/placeholders/RoundShape.js" {
  declare module.exports: $Exports<
    "react-placeholder/lib/placeholders/RoundShape"
  >;
}
declare module "react-placeholder/lib/placeholders/TextBlock.js" {
  declare module.exports: $Exports<
    "react-placeholder/lib/placeholders/TextBlock"
  >;
}
declare module "react-placeholder/lib/placeholders/TextRow.js" {
  declare module.exports: $Exports<
    "react-placeholder/lib/placeholders/TextRow"
  >;
}
declare module "react-placeholder/lib/ReactPlaceholder.js" {
  declare module.exports: $Exports<"react-placeholder/lib/ReactPlaceholder">;
}
