// flow-typed signature: da9d74045475435ef64560e4b4b4c138
// flow-typed version: <<STUB>>/swagger-client_v^3.0.14/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swagger-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "swagger-client" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "swagger-client/dist/index" {
  declare module.exports: any;
}

// Filename aliases
declare module "swagger-client/dist/index.js" {
  declare module.exports: $Exports<"swagger-client/dist/index">;
}
