// flow-typed signature: fd4807faecc6c3dbf7779176cc30743c
// flow-typed version: <<STUB>>/swagger-ts-generator_v^1.1.17/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swagger-ts-generator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "swagger-ts-generator" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "swagger-ts-generator/lib/enumGenerator" {
  declare module.exports: any;
}

declare module "swagger-ts-generator/lib/modelGenerator" {
  declare module.exports: any;
}

declare module "swagger-ts-generator/lib/utils" {
  declare module.exports: any;
}

// Filename aliases
declare module "swagger-ts-generator/index" {
  declare module.exports: $Exports<"swagger-ts-generator">;
}
declare module "swagger-ts-generator/index.js" {
  declare module.exports: $Exports<"swagger-ts-generator">;
}
declare module "swagger-ts-generator/lib/enumGenerator.js" {
  declare module.exports: $Exports<"swagger-ts-generator/lib/enumGenerator">;
}
declare module "swagger-ts-generator/lib/modelGenerator.js" {
  declare module.exports: $Exports<"swagger-ts-generator/lib/modelGenerator">;
}
declare module "swagger-ts-generator/lib/utils.js" {
  declare module.exports: $Exports<"swagger-ts-generator/lib/utils">;
}
