// flow-typed signature: b06e49488db900ed50cb90a20414208f
// flow-typed version: <<STUB>>/swagger-js-codegen_v^1.10.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swagger-js-codegen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "swagger-js-codegen" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "swagger-js-codegen/bin/swagger2ts" {
  declare module.exports: any;
}

declare module "swagger-js-codegen/Gruntfile" {
  declare module.exports: any;
}

declare module "swagger-js-codegen/lib/cli" {
  declare module.exports: any;
}

declare module "swagger-js-codegen/lib/codegen" {
  declare module.exports: any;
}

declare module "swagger-js-codegen/lib/typescript" {
  declare module.exports: any;
}

declare module "swagger-js-codegen/tests/generation" {
  declare module.exports: any;
}

// Filename aliases
declare module "swagger-js-codegen/bin/swagger2ts.js" {
  declare module.exports: $Exports<"swagger-js-codegen/bin/swagger2ts">;
}
declare module "swagger-js-codegen/Gruntfile.js" {
  declare module.exports: $Exports<"swagger-js-codegen/Gruntfile">;
}
declare module "swagger-js-codegen/lib/cli.js" {
  declare module.exports: $Exports<"swagger-js-codegen/lib/cli">;
}
declare module "swagger-js-codegen/lib/codegen.js" {
  declare module.exports: $Exports<"swagger-js-codegen/lib/codegen">;
}
declare module "swagger-js-codegen/lib/typescript.js" {
  declare module.exports: $Exports<"swagger-js-codegen/lib/typescript">;
}
declare module "swagger-js-codegen/tests/generation.js" {
  declare module.exports: $Exports<"swagger-js-codegen/tests/generation">;
}
