// flow-typed signature: 055e482769205348e1f63d5777795906
// flow-typed version: <<STUB>>/sweetalert-react_v^0.4.10/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sweetalert-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "sweetalert-react" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "sweetalert-react/lib/index" {
  declare module.exports: any;
}

declare module "sweetalert-react/lib/SweetAlert" {
  declare module.exports: any;
}

declare module "sweetalert-react/lib/utils/__mocks__/isDOMEquals" {
  declare module.exports: any;
}

declare module "sweetalert-react/lib/utils/isDOMEquals" {
  declare module.exports: any;
}

declare module "sweetalert-react/lib/utils/outsideTargetHandlerFactory" {
  declare module.exports: any;
}

// Filename aliases
declare module "sweetalert-react/lib/index.js" {
  declare module.exports: $Exports<"sweetalert-react/lib/index">;
}
declare module "sweetalert-react/lib/SweetAlert.js" {
  declare module.exports: $Exports<"sweetalert-react/lib/SweetAlert">;
}
declare module "sweetalert-react/lib/utils/__mocks__/isDOMEquals.js" {
  declare module.exports: $Exports<
    "sweetalert-react/lib/utils/__mocks__/isDOMEquals"
  >;
}
declare module "sweetalert-react/lib/utils/isDOMEquals.js" {
  declare module.exports: $Exports<"sweetalert-react/lib/utils/isDOMEquals">;
}
declare module "sweetalert-react/lib/utils/outsideTargetHandlerFactory.js" {
  declare module.exports: $Exports<
    "sweetalert-react/lib/utils/outsideTargetHandlerFactory"
  >;
}
