// flow-typed signature: 95f66ee1f516fe3cfc13c8f2b63b0ebd
// flow-typed version: <<STUB>>/ts-protoc-gen_v^0.3.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ts-protoc-gen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "ts-protoc-gen" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "ts-protoc-gen/lib/ExportMap" {
  declare module.exports: any;
}

declare module "ts-protoc-gen/lib/js_service_index" {
  declare module.exports: any;
}

declare module "ts-protoc-gen/lib/js/fileDescriptorJSServices" {
  declare module.exports: any;
}

declare module "ts-protoc-gen/lib/Printer" {
  declare module.exports: any;
}

declare module "ts-protoc-gen/lib/ts_index" {
  declare module.exports: any;
}

declare module "ts-protoc-gen/lib/ts/enum" {
  declare module.exports: any;
}

declare module "ts-protoc-gen/lib/ts/extensions" {
  declare module.exports: any;
}

declare module "ts-protoc-gen/lib/ts/FieldTypes" {
  declare module.exports: any;
}

declare module "ts-protoc-gen/lib/ts/fileDescriptorTSD" {
  declare module.exports: any;
}

declare module "ts-protoc-gen/lib/ts/fileDescriptorTSServices" {
  declare module.exports: any;
}

declare module "ts-protoc-gen/lib/ts/message" {
  declare module.exports: any;
}

declare module "ts-protoc-gen/lib/ts/oneof" {
  declare module.exports: any;
}

declare module "ts-protoc-gen/lib/util" {
  declare module.exports: any;
}

declare module "ts-protoc-gen/lib/WellKnown" {
  declare module.exports: any;
}

// Filename aliases
declare module "ts-protoc-gen/lib/ExportMap.js" {
  declare module.exports: $Exports<"ts-protoc-gen/lib/ExportMap">;
}
declare module "ts-protoc-gen/lib/js_service_index.js" {
  declare module.exports: $Exports<"ts-protoc-gen/lib/js_service_index">;
}
declare module "ts-protoc-gen/lib/js/fileDescriptorJSServices.js" {
  declare module.exports: $Exports<
    "ts-protoc-gen/lib/js/fileDescriptorJSServices"
  >;
}
declare module "ts-protoc-gen/lib/Printer.js" {
  declare module.exports: $Exports<"ts-protoc-gen/lib/Printer">;
}
declare module "ts-protoc-gen/lib/ts_index.js" {
  declare module.exports: $Exports<"ts-protoc-gen/lib/ts_index">;
}
declare module "ts-protoc-gen/lib/ts/enum.js" {
  declare module.exports: $Exports<"ts-protoc-gen/lib/ts/enum">;
}
declare module "ts-protoc-gen/lib/ts/extensions.js" {
  declare module.exports: $Exports<"ts-protoc-gen/lib/ts/extensions">;
}
declare module "ts-protoc-gen/lib/ts/FieldTypes.js" {
  declare module.exports: $Exports<"ts-protoc-gen/lib/ts/FieldTypes">;
}
declare module "ts-protoc-gen/lib/ts/fileDescriptorTSD.js" {
  declare module.exports: $Exports<"ts-protoc-gen/lib/ts/fileDescriptorTSD">;
}
declare module "ts-protoc-gen/lib/ts/fileDescriptorTSServices.js" {
  declare module.exports: $Exports<
    "ts-protoc-gen/lib/ts/fileDescriptorTSServices"
  >;
}
declare module "ts-protoc-gen/lib/ts/message.js" {
  declare module.exports: $Exports<"ts-protoc-gen/lib/ts/message">;
}
declare module "ts-protoc-gen/lib/ts/oneof.js" {
  declare module.exports: $Exports<"ts-protoc-gen/lib/ts/oneof">;
}
declare module "ts-protoc-gen/lib/util.js" {
  declare module.exports: $Exports<"ts-protoc-gen/lib/util">;
}
declare module "ts-protoc-gen/lib/WellKnown.js" {
  declare module.exports: $Exports<"ts-protoc-gen/lib/WellKnown">;
}
