// flow-typed signature: 341da19b33e89ce28596ca7bec8c5637
// flow-typed version: <<STUB>>/uppy_v^0.16.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uppy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "uppy" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "uppy/bin/build-css" {
  declare module.exports: any;
}

declare module "uppy/bin/build-js" {
  declare module.exports: any;
}

declare module "uppy/bin/gzip" {
  declare module.exports: any;
}

declare module "uppy/dist/uppy" {
  declare module.exports: any;
}

declare module "uppy/dist/uppy.min" {
  declare module.exports: any;
}

declare module "uppy/example/bundle" {
  declare module.exports: any;
}

declare module "uppy/example/main" {
  declare module.exports: any;
}

declare module "uppy/lib/core/Core" {
  declare module.exports: any;
}

declare module "uppy/lib/core/index" {
  declare module.exports: any;
}

declare module "uppy/lib/core/Translator" {
  declare module.exports: any;
}

declare module "uppy/lib/core/UppySocket" {
  declare module.exports: any;
}

declare module "uppy/lib/core/Utils" {
  declare module.exports: any;
}

declare module "uppy/lib/generic-provider-views/AuthView" {
  declare module.exports: any;
}

declare module "uppy/lib/generic-provider-views/Breadcrumb" {
  declare module.exports: any;
}

declare module "uppy/lib/generic-provider-views/Breadcrumbs" {
  declare module.exports: any;
}

declare module "uppy/lib/generic-provider-views/Browser" {
  declare module.exports: any;
}

declare module "uppy/lib/generic-provider-views/Error" {
  declare module.exports: any;
}

declare module "uppy/lib/generic-provider-views/index" {
  declare module.exports: any;
}

declare module "uppy/lib/generic-provider-views/Loader" {
  declare module.exports: any;
}

declare module "uppy/lib/generic-provider-views/Table" {
  declare module.exports: any;
}

declare module "uppy/lib/generic-provider-views/TableColumn" {
  declare module.exports: any;
}

declare module "uppy/lib/generic-provider-views/TableRow" {
  declare module.exports: any;
}

declare module "uppy/lib/index" {
  declare module.exports: any;
}

declare module "uppy/lib/locales/en_US" {
  declare module.exports: any;
}

declare module "uppy/lib/locales/it_IT" {
  declare module.exports: any;
}

declare module "uppy/lib/locales/pt_BR" {
  declare module.exports: any;
}

declare module "uppy/lib/locales/ru_RU" {
  declare module.exports: any;
}

declare module "uppy/lib/locales/zh_CN" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/_index" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Dashboard/ActionBrowseTagline" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Dashboard/Dashboard" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Dashboard/FileCard" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Dashboard/FileItem" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Dashboard/FileItemProgress" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Dashboard/FileList" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Dashboard/getFileTypeIcon" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Dashboard/icons" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Dashboard/index" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Dashboard/StatusBar" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Dashboard/Tabs" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Dashboard/UploadBtn" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/DragDrop/index" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Dropbox/icons" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Dropbox/index" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Dummy" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/FileInput" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/GoogleDrive/index" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Informer" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/MagicLog" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/MetaData" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Multipart" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/PersistentState" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Plugin" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/ProgressBar" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Transloadit/Client" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Transloadit/index" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Transloadit/Socket" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Tus10" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Webcam/CameraIcon" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Webcam/CameraScreen" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Webcam/index" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Webcam/PermissionsScreen" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Webcam/RecordButton" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Webcam/RecordStartIcon" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Webcam/RecordStopIcon" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Webcam/SnapshotButton" {
  declare module.exports: any;
}

declare module "uppy/lib/plugins/Webcam/WebcamIcon" {
  declare module.exports: any;
}

declare module "uppy/lib/uppy-base/src/index" {
  declare module.exports: any;
}

declare module "uppy/lib/uppy-base/src/plugins/Provider" {
  declare module.exports: any;
}

declare module "uppy/lib/uppy-base/src/plugins/Webcam" {
  declare module.exports: any;
}

declare module "uppy/lib/uppy-base/src/utils/dataURItoFile" {
  declare module.exports: any;
}

declare module "uppy/lib/uppy-base/src/utils/toArray" {
  declare module.exports: any;
}

declare module "uppy/lib/uppy-base/src/utils/UppySocket" {
  declare module.exports: any;
}

declare module "uppy/src/core/Core" {
  declare module.exports: any;
}

declare module "uppy/src/core/index" {
  declare module.exports: any;
}

declare module "uppy/src/core/Translator" {
  declare module.exports: any;
}

declare module "uppy/src/core/UppySocket" {
  declare module.exports: any;
}

declare module "uppy/src/core/Utils" {
  declare module.exports: any;
}

declare module "uppy/src/generic-provider-views/AuthView" {
  declare module.exports: any;
}

declare module "uppy/src/generic-provider-views/Breadcrumb" {
  declare module.exports: any;
}

declare module "uppy/src/generic-provider-views/Breadcrumbs" {
  declare module.exports: any;
}

declare module "uppy/src/generic-provider-views/Browser" {
  declare module.exports: any;
}

declare module "uppy/src/generic-provider-views/Error" {
  declare module.exports: any;
}

declare module "uppy/src/generic-provider-views/index" {
  declare module.exports: any;
}

declare module "uppy/src/generic-provider-views/Loader" {
  declare module.exports: any;
}

declare module "uppy/src/generic-provider-views/Table" {
  declare module.exports: any;
}

declare module "uppy/src/generic-provider-views/TableColumn" {
  declare module.exports: any;
}

declare module "uppy/src/generic-provider-views/TableRow" {
  declare module.exports: any;
}

declare module "uppy/src/index" {
  declare module.exports: any;
}

declare module "uppy/src/locales/en_US" {
  declare module.exports: any;
}

declare module "uppy/src/locales/it_IT" {
  declare module.exports: any;
}

declare module "uppy/src/locales/pt_BR" {
  declare module.exports: any;
}

declare module "uppy/src/locales/ru_RU" {
  declare module.exports: any;
}

declare module "uppy/src/locales/zh_CN" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/_index" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Dashboard/ActionBrowseTagline" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Dashboard/Dashboard" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Dashboard/FileCard" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Dashboard/FileItem" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Dashboard/FileItemProgress" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Dashboard/FileList" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Dashboard/getFileTypeIcon" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Dashboard/icons" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Dashboard/index" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Dashboard/StatusBar" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Dashboard/Tabs" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Dashboard/UploadBtn" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/DragDrop/index" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Dropbox/icons" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Dropbox/index" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Dummy" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/FileInput" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/GoogleDrive/index" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Informer" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/MagicLog" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/MetaData" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Multipart" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/PersistentState" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Plugin" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/ProgressBar" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Transloadit/Client" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Transloadit/index" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Transloadit/Socket" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Tus10" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Webcam/CameraIcon" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Webcam/CameraScreen" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Webcam/index" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Webcam/PermissionsScreen" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Webcam/RecordButton" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Webcam/RecordStartIcon" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Webcam/RecordStopIcon" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Webcam/SnapshotButton" {
  declare module.exports: any;
}

declare module "uppy/src/plugins/Webcam/WebcamIcon" {
  declare module.exports: any;
}

declare module "uppy/src/uppy-base/src/index" {
  declare module.exports: any;
}

declare module "uppy/src/uppy-base/src/plugins/Provider" {
  declare module.exports: any;
}

declare module "uppy/src/uppy-base/src/plugins/Webcam" {
  declare module.exports: any;
}

declare module "uppy/src/uppy-base/src/utils/dataURItoFile" {
  declare module.exports: any;
}

declare module "uppy/src/uppy-base/src/utils/toArray" {
  declare module.exports: any;
}

declare module "uppy/src/uppy-base/src/utils/UppySocket" {
  declare module.exports: any;
}

declare module "uppy/test/acceptance/dragdrop.spec" {
  declare module.exports: any;
}

declare module "uppy/test/acceptance/dummy.spec" {
  declare module.exports: any;
}

declare module "uppy/test/acceptance/fallback.spec" {
  declare module.exports: any;
}

declare module "uppy/test/acceptance/i18n.spec" {
  declare module.exports: any;
}

declare module "uppy/test/acceptance/index" {
  declare module.exports: any;
}

declare module "uppy/test/acceptance/multipart.spec" {
  declare module.exports: any;
}

declare module "uppy/test/acceptance/saucelabs-dummy.spec" {
  declare module.exports: any;
}

declare module "uppy/test/acceptance/tools" {
  declare module.exports: any;
}

declare module "uppy/test/unit/core.spec" {
  declare module.exports: any;
}

declare module "uppy/test/unit/GoogleDrive.spec" {
  declare module.exports: any;
}

declare module "uppy/test/unit/index" {
  declare module.exports: any;
}

declare module "uppy/test/unit/mocks/plugin-acquirer1" {
  declare module.exports: any;
}

declare module "uppy/test/unit/mocks/plugin-acquirer2" {
  declare module.exports: any;
}

declare module "uppy/test/unit/spec/fakeBlob" {
  declare module.exports: any;
}

declare module "uppy/test/unit/spec/uppy" {
  declare module.exports: any;
}

declare module "uppy/test/unit/translator.spec" {
  declare module.exports: any;
}

declare module "uppy/test/unit/Transloadit.spec" {
  declare module.exports: any;
}

// Filename aliases
declare module "uppy/bin/build-css.js" {
  declare module.exports: $Exports<"uppy/bin/build-css">;
}
declare module "uppy/bin/build-js.js" {
  declare module.exports: $Exports<"uppy/bin/build-js">;
}
declare module "uppy/bin/gzip.js" {
  declare module.exports: $Exports<"uppy/bin/gzip">;
}
declare module "uppy/dist/uppy.js" {
  declare module.exports: $Exports<"uppy/dist/uppy">;
}
declare module "uppy/dist/uppy.min.js" {
  declare module.exports: $Exports<"uppy/dist/uppy.min">;
}
declare module "uppy/example/bundle.js" {
  declare module.exports: $Exports<"uppy/example/bundle">;
}
declare module "uppy/example/main.js" {
  declare module.exports: $Exports<"uppy/example/main">;
}
declare module "uppy/lib/core/Core.js" {
  declare module.exports: $Exports<"uppy/lib/core/Core">;
}
declare module "uppy/lib/core/index.js" {
  declare module.exports: $Exports<"uppy/lib/core/index">;
}
declare module "uppy/lib/core/Translator.js" {
  declare module.exports: $Exports<"uppy/lib/core/Translator">;
}
declare module "uppy/lib/core/UppySocket.js" {
  declare module.exports: $Exports<"uppy/lib/core/UppySocket">;
}
declare module "uppy/lib/core/Utils.js" {
  declare module.exports: $Exports<"uppy/lib/core/Utils">;
}
declare module "uppy/lib/generic-provider-views/AuthView.js" {
  declare module.exports: $Exports<"uppy/lib/generic-provider-views/AuthView">;
}
declare module "uppy/lib/generic-provider-views/Breadcrumb.js" {
  declare module.exports: $Exports<
    "uppy/lib/generic-provider-views/Breadcrumb"
  >;
}
declare module "uppy/lib/generic-provider-views/Breadcrumbs.js" {
  declare module.exports: $Exports<
    "uppy/lib/generic-provider-views/Breadcrumbs"
  >;
}
declare module "uppy/lib/generic-provider-views/Browser.js" {
  declare module.exports: $Exports<"uppy/lib/generic-provider-views/Browser">;
}
declare module "uppy/lib/generic-provider-views/Error.js" {
  declare module.exports: $Exports<"uppy/lib/generic-provider-views/Error">;
}
declare module "uppy/lib/generic-provider-views/index.js" {
  declare module.exports: $Exports<"uppy/lib/generic-provider-views/index">;
}
declare module "uppy/lib/generic-provider-views/Loader.js" {
  declare module.exports: $Exports<"uppy/lib/generic-provider-views/Loader">;
}
declare module "uppy/lib/generic-provider-views/Table.js" {
  declare module.exports: $Exports<"uppy/lib/generic-provider-views/Table">;
}
declare module "uppy/lib/generic-provider-views/TableColumn.js" {
  declare module.exports: $Exports<
    "uppy/lib/generic-provider-views/TableColumn"
  >;
}
declare module "uppy/lib/generic-provider-views/TableRow.js" {
  declare module.exports: $Exports<"uppy/lib/generic-provider-views/TableRow">;
}
declare module "uppy/lib/index.js" {
  declare module.exports: $Exports<"uppy/lib/index">;
}
declare module "uppy/lib/locales/en_US.js" {
  declare module.exports: $Exports<"uppy/lib/locales/en_US">;
}
declare module "uppy/lib/locales/it_IT.js" {
  declare module.exports: $Exports<"uppy/lib/locales/it_IT">;
}
declare module "uppy/lib/locales/pt_BR.js" {
  declare module.exports: $Exports<"uppy/lib/locales/pt_BR">;
}
declare module "uppy/lib/locales/ru_RU.js" {
  declare module.exports: $Exports<"uppy/lib/locales/ru_RU">;
}
declare module "uppy/lib/locales/zh_CN.js" {
  declare module.exports: $Exports<"uppy/lib/locales/zh_CN">;
}
declare module "uppy/lib/plugins/_index.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/_index">;
}
declare module "uppy/lib/plugins/Dashboard/ActionBrowseTagline.js" {
  declare module.exports: $Exports<
    "uppy/lib/plugins/Dashboard/ActionBrowseTagline"
  >;
}
declare module "uppy/lib/plugins/Dashboard/Dashboard.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Dashboard/Dashboard">;
}
declare module "uppy/lib/plugins/Dashboard/FileCard.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Dashboard/FileCard">;
}
declare module "uppy/lib/plugins/Dashboard/FileItem.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Dashboard/FileItem">;
}
declare module "uppy/lib/plugins/Dashboard/FileItemProgress.js" {
  declare module.exports: $Exports<
    "uppy/lib/plugins/Dashboard/FileItemProgress"
  >;
}
declare module "uppy/lib/plugins/Dashboard/FileList.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Dashboard/FileList">;
}
declare module "uppy/lib/plugins/Dashboard/getFileTypeIcon.js" {
  declare module.exports: $Exports<
    "uppy/lib/plugins/Dashboard/getFileTypeIcon"
  >;
}
declare module "uppy/lib/plugins/Dashboard/icons.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Dashboard/icons">;
}
declare module "uppy/lib/plugins/Dashboard/index.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Dashboard/index">;
}
declare module "uppy/lib/plugins/Dashboard/StatusBar.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Dashboard/StatusBar">;
}
declare module "uppy/lib/plugins/Dashboard/Tabs.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Dashboard/Tabs">;
}
declare module "uppy/lib/plugins/Dashboard/UploadBtn.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Dashboard/UploadBtn">;
}
declare module "uppy/lib/plugins/DragDrop/index.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/DragDrop/index">;
}
declare module "uppy/lib/plugins/Dropbox/icons.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Dropbox/icons">;
}
declare module "uppy/lib/plugins/Dropbox/index.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Dropbox/index">;
}
declare module "uppy/lib/plugins/Dummy.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Dummy">;
}
declare module "uppy/lib/plugins/FileInput.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/FileInput">;
}
declare module "uppy/lib/plugins/GoogleDrive/index.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/GoogleDrive/index">;
}
declare module "uppy/lib/plugins/Informer.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Informer">;
}
declare module "uppy/lib/plugins/MagicLog.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/MagicLog">;
}
declare module "uppy/lib/plugins/MetaData.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/MetaData">;
}
declare module "uppy/lib/plugins/Multipart.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Multipart">;
}
declare module "uppy/lib/plugins/PersistentState.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/PersistentState">;
}
declare module "uppy/lib/plugins/Plugin.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Plugin">;
}
declare module "uppy/lib/plugins/ProgressBar.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/ProgressBar">;
}
declare module "uppy/lib/plugins/Transloadit/Client.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Transloadit/Client">;
}
declare module "uppy/lib/plugins/Transloadit/index.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Transloadit/index">;
}
declare module "uppy/lib/plugins/Transloadit/Socket.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Transloadit/Socket">;
}
declare module "uppy/lib/plugins/Tus10.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Tus10">;
}
declare module "uppy/lib/plugins/Webcam/CameraIcon.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Webcam/CameraIcon">;
}
declare module "uppy/lib/plugins/Webcam/CameraScreen.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Webcam/CameraScreen">;
}
declare module "uppy/lib/plugins/Webcam/index.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Webcam/index">;
}
declare module "uppy/lib/plugins/Webcam/PermissionsScreen.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Webcam/PermissionsScreen">;
}
declare module "uppy/lib/plugins/Webcam/RecordButton.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Webcam/RecordButton">;
}
declare module "uppy/lib/plugins/Webcam/RecordStartIcon.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Webcam/RecordStartIcon">;
}
declare module "uppy/lib/plugins/Webcam/RecordStopIcon.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Webcam/RecordStopIcon">;
}
declare module "uppy/lib/plugins/Webcam/SnapshotButton.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Webcam/SnapshotButton">;
}
declare module "uppy/lib/plugins/Webcam/WebcamIcon.js" {
  declare module.exports: $Exports<"uppy/lib/plugins/Webcam/WebcamIcon">;
}
declare module "uppy/lib/uppy-base/src/index.js" {
  declare module.exports: $Exports<"uppy/lib/uppy-base/src/index">;
}
declare module "uppy/lib/uppy-base/src/plugins/Provider.js" {
  declare module.exports: $Exports<"uppy/lib/uppy-base/src/plugins/Provider">;
}
declare module "uppy/lib/uppy-base/src/plugins/Webcam.js" {
  declare module.exports: $Exports<"uppy/lib/uppy-base/src/plugins/Webcam">;
}
declare module "uppy/lib/uppy-base/src/utils/dataURItoFile.js" {
  declare module.exports: $Exports<
    "uppy/lib/uppy-base/src/utils/dataURItoFile"
  >;
}
declare module "uppy/lib/uppy-base/src/utils/toArray.js" {
  declare module.exports: $Exports<"uppy/lib/uppy-base/src/utils/toArray">;
}
declare module "uppy/lib/uppy-base/src/utils/UppySocket.js" {
  declare module.exports: $Exports<"uppy/lib/uppy-base/src/utils/UppySocket">;
}
declare module "uppy/src/core/Core.js" {
  declare module.exports: $Exports<"uppy/src/core/Core">;
}
declare module "uppy/src/core/index.js" {
  declare module.exports: $Exports<"uppy/src/core/index">;
}
declare module "uppy/src/core/Translator.js" {
  declare module.exports: $Exports<"uppy/src/core/Translator">;
}
declare module "uppy/src/core/UppySocket.js" {
  declare module.exports: $Exports<"uppy/src/core/UppySocket">;
}
declare module "uppy/src/core/Utils.js" {
  declare module.exports: $Exports<"uppy/src/core/Utils">;
}
declare module "uppy/src/generic-provider-views/AuthView.js" {
  declare module.exports: $Exports<"uppy/src/generic-provider-views/AuthView">;
}
declare module "uppy/src/generic-provider-views/Breadcrumb.js" {
  declare module.exports: $Exports<
    "uppy/src/generic-provider-views/Breadcrumb"
  >;
}
declare module "uppy/src/generic-provider-views/Breadcrumbs.js" {
  declare module.exports: $Exports<
    "uppy/src/generic-provider-views/Breadcrumbs"
  >;
}
declare module "uppy/src/generic-provider-views/Browser.js" {
  declare module.exports: $Exports<"uppy/src/generic-provider-views/Browser">;
}
declare module "uppy/src/generic-provider-views/Error.js" {
  declare module.exports: $Exports<"uppy/src/generic-provider-views/Error">;
}
declare module "uppy/src/generic-provider-views/index.js" {
  declare module.exports: $Exports<"uppy/src/generic-provider-views/index">;
}
declare module "uppy/src/generic-provider-views/Loader.js" {
  declare module.exports: $Exports<"uppy/src/generic-provider-views/Loader">;
}
declare module "uppy/src/generic-provider-views/Table.js" {
  declare module.exports: $Exports<"uppy/src/generic-provider-views/Table">;
}
declare module "uppy/src/generic-provider-views/TableColumn.js" {
  declare module.exports: $Exports<
    "uppy/src/generic-provider-views/TableColumn"
  >;
}
declare module "uppy/src/generic-provider-views/TableRow.js" {
  declare module.exports: $Exports<"uppy/src/generic-provider-views/TableRow">;
}
declare module "uppy/src/index.js" {
  declare module.exports: $Exports<"uppy/src/index">;
}
declare module "uppy/src/locales/en_US.js" {
  declare module.exports: $Exports<"uppy/src/locales/en_US">;
}
declare module "uppy/src/locales/it_IT.js" {
  declare module.exports: $Exports<"uppy/src/locales/it_IT">;
}
declare module "uppy/src/locales/pt_BR.js" {
  declare module.exports: $Exports<"uppy/src/locales/pt_BR">;
}
declare module "uppy/src/locales/ru_RU.js" {
  declare module.exports: $Exports<"uppy/src/locales/ru_RU">;
}
declare module "uppy/src/locales/zh_CN.js" {
  declare module.exports: $Exports<"uppy/src/locales/zh_CN">;
}
declare module "uppy/src/plugins/_index.js" {
  declare module.exports: $Exports<"uppy/src/plugins/_index">;
}
declare module "uppy/src/plugins/Dashboard/ActionBrowseTagline.js" {
  declare module.exports: $Exports<
    "uppy/src/plugins/Dashboard/ActionBrowseTagline"
  >;
}
declare module "uppy/src/plugins/Dashboard/Dashboard.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Dashboard/Dashboard">;
}
declare module "uppy/src/plugins/Dashboard/FileCard.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Dashboard/FileCard">;
}
declare module "uppy/src/plugins/Dashboard/FileItem.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Dashboard/FileItem">;
}
declare module "uppy/src/plugins/Dashboard/FileItemProgress.js" {
  declare module.exports: $Exports<
    "uppy/src/plugins/Dashboard/FileItemProgress"
  >;
}
declare module "uppy/src/plugins/Dashboard/FileList.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Dashboard/FileList">;
}
declare module "uppy/src/plugins/Dashboard/getFileTypeIcon.js" {
  declare module.exports: $Exports<
    "uppy/src/plugins/Dashboard/getFileTypeIcon"
  >;
}
declare module "uppy/src/plugins/Dashboard/icons.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Dashboard/icons">;
}
declare module "uppy/src/plugins/Dashboard/index.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Dashboard/index">;
}
declare module "uppy/src/plugins/Dashboard/StatusBar.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Dashboard/StatusBar">;
}
declare module "uppy/src/plugins/Dashboard/Tabs.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Dashboard/Tabs">;
}
declare module "uppy/src/plugins/Dashboard/UploadBtn.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Dashboard/UploadBtn">;
}
declare module "uppy/src/plugins/DragDrop/index.js" {
  declare module.exports: $Exports<"uppy/src/plugins/DragDrop/index">;
}
declare module "uppy/src/plugins/Dropbox/icons.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Dropbox/icons">;
}
declare module "uppy/src/plugins/Dropbox/index.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Dropbox/index">;
}
declare module "uppy/src/plugins/Dummy.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Dummy">;
}
declare module "uppy/src/plugins/FileInput.js" {
  declare module.exports: $Exports<"uppy/src/plugins/FileInput">;
}
declare module "uppy/src/plugins/GoogleDrive/index.js" {
  declare module.exports: $Exports<"uppy/src/plugins/GoogleDrive/index">;
}
declare module "uppy/src/plugins/Informer.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Informer">;
}
declare module "uppy/src/plugins/MagicLog.js" {
  declare module.exports: $Exports<"uppy/src/plugins/MagicLog">;
}
declare module "uppy/src/plugins/MetaData.js" {
  declare module.exports: $Exports<"uppy/src/plugins/MetaData">;
}
declare module "uppy/src/plugins/Multipart.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Multipart">;
}
declare module "uppy/src/plugins/PersistentState.js" {
  declare module.exports: $Exports<"uppy/src/plugins/PersistentState">;
}
declare module "uppy/src/plugins/Plugin.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Plugin">;
}
declare module "uppy/src/plugins/ProgressBar.js" {
  declare module.exports: $Exports<"uppy/src/plugins/ProgressBar">;
}
declare module "uppy/src/plugins/Transloadit/Client.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Transloadit/Client">;
}
declare module "uppy/src/plugins/Transloadit/index.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Transloadit/index">;
}
declare module "uppy/src/plugins/Transloadit/Socket.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Transloadit/Socket">;
}
declare module "uppy/src/plugins/Tus10.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Tus10">;
}
declare module "uppy/src/plugins/Webcam/CameraIcon.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Webcam/CameraIcon">;
}
declare module "uppy/src/plugins/Webcam/CameraScreen.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Webcam/CameraScreen">;
}
declare module "uppy/src/plugins/Webcam/index.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Webcam/index">;
}
declare module "uppy/src/plugins/Webcam/PermissionsScreen.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Webcam/PermissionsScreen">;
}
declare module "uppy/src/plugins/Webcam/RecordButton.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Webcam/RecordButton">;
}
declare module "uppy/src/plugins/Webcam/RecordStartIcon.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Webcam/RecordStartIcon">;
}
declare module "uppy/src/plugins/Webcam/RecordStopIcon.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Webcam/RecordStopIcon">;
}
declare module "uppy/src/plugins/Webcam/SnapshotButton.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Webcam/SnapshotButton">;
}
declare module "uppy/src/plugins/Webcam/WebcamIcon.js" {
  declare module.exports: $Exports<"uppy/src/plugins/Webcam/WebcamIcon">;
}
declare module "uppy/src/uppy-base/src/index.js" {
  declare module.exports: $Exports<"uppy/src/uppy-base/src/index">;
}
declare module "uppy/src/uppy-base/src/plugins/Provider.js" {
  declare module.exports: $Exports<"uppy/src/uppy-base/src/plugins/Provider">;
}
declare module "uppy/src/uppy-base/src/plugins/Webcam.js" {
  declare module.exports: $Exports<"uppy/src/uppy-base/src/plugins/Webcam">;
}
declare module "uppy/src/uppy-base/src/utils/dataURItoFile.js" {
  declare module.exports: $Exports<
    "uppy/src/uppy-base/src/utils/dataURItoFile"
  >;
}
declare module "uppy/src/uppy-base/src/utils/toArray.js" {
  declare module.exports: $Exports<"uppy/src/uppy-base/src/utils/toArray">;
}
declare module "uppy/src/uppy-base/src/utils/UppySocket.js" {
  declare module.exports: $Exports<"uppy/src/uppy-base/src/utils/UppySocket">;
}
declare module "uppy/test/acceptance/dragdrop.spec.js" {
  declare module.exports: $Exports<"uppy/test/acceptance/dragdrop.spec">;
}
declare module "uppy/test/acceptance/dummy.spec.js" {
  declare module.exports: $Exports<"uppy/test/acceptance/dummy.spec">;
}
declare module "uppy/test/acceptance/fallback.spec.js" {
  declare module.exports: $Exports<"uppy/test/acceptance/fallback.spec">;
}
declare module "uppy/test/acceptance/i18n.spec.js" {
  declare module.exports: $Exports<"uppy/test/acceptance/i18n.spec">;
}
declare module "uppy/test/acceptance/index.js" {
  declare module.exports: $Exports<"uppy/test/acceptance/index">;
}
declare module "uppy/test/acceptance/multipart.spec.js" {
  declare module.exports: $Exports<"uppy/test/acceptance/multipart.spec">;
}
declare module "uppy/test/acceptance/saucelabs-dummy.spec.js" {
  declare module.exports: $Exports<"uppy/test/acceptance/saucelabs-dummy.spec">;
}
declare module "uppy/test/acceptance/tools.js" {
  declare module.exports: $Exports<"uppy/test/acceptance/tools">;
}
declare module "uppy/test/unit/core.spec.js" {
  declare module.exports: $Exports<"uppy/test/unit/core.spec">;
}
declare module "uppy/test/unit/GoogleDrive.spec.js" {
  declare module.exports: $Exports<"uppy/test/unit/GoogleDrive.spec">;
}
declare module "uppy/test/unit/index.js" {
  declare module.exports: $Exports<"uppy/test/unit/index">;
}
declare module "uppy/test/unit/mocks/plugin-acquirer1.js" {
  declare module.exports: $Exports<"uppy/test/unit/mocks/plugin-acquirer1">;
}
declare module "uppy/test/unit/mocks/plugin-acquirer2.js" {
  declare module.exports: $Exports<"uppy/test/unit/mocks/plugin-acquirer2">;
}
declare module "uppy/test/unit/spec/fakeBlob.js" {
  declare module.exports: $Exports<"uppy/test/unit/spec/fakeBlob">;
}
declare module "uppy/test/unit/spec/uppy.js" {
  declare module.exports: $Exports<"uppy/test/unit/spec/uppy">;
}
declare module "uppy/test/unit/translator.spec.js" {
  declare module.exports: $Exports<"uppy/test/unit/translator.spec">;
}
declare module "uppy/test/unit/Transloadit.spec.js" {
  declare module.exports: $Exports<"uppy/test/unit/Transloadit.spec">;
}
