// flow-typed signature: ebf1582aca9e154b32bc67ede0abd8cb
// flow-typed version: <<STUB>>/yeast_v^0.1.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yeast'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "yeast" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "yeast/index" {
  declare module.exports: $Exports<"yeast">;
}
declare module "yeast/index.js" {
  declare module.exports: $Exports<"yeast">;
}
