// flow-typed signature: 484e82b312c44f88f67db561a7e21ddd
// flow-typed version: <<STUB>>/@cerebral/http_v^0.0.0-beta.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@cerebral/http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@cerebral/http" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@cerebral/http/lib/DEFAULT_OPTIONS" {
  declare module.exports: any;
}

declare module "@cerebral/http/lib/fileUpload" {
  declare module.exports: any;
}

declare module "@cerebral/http/lib/HttpProviderError" {
  declare module.exports: any;
}

declare module "@cerebral/http/lib/index" {
  declare module.exports: any;
}

declare module "@cerebral/http/lib/operators/httpDelete" {
  declare module.exports: any;
}

declare module "@cerebral/http/lib/operators/httpGet" {
  declare module.exports: any;
}

declare module "@cerebral/http/lib/operators/httpPatch" {
  declare module.exports: any;
}

declare module "@cerebral/http/lib/operators/httpPost" {
  declare module.exports: any;
}

declare module "@cerebral/http/lib/operators/httpPut" {
  declare module.exports: any;
}

declare module "@cerebral/http/lib/operators/httpUploadFile" {
  declare module.exports: any;
}

declare module "@cerebral/http/lib/operators/index" {
  declare module.exports: any;
}

declare module "@cerebral/http/lib/request" {
  declare module.exports: any;
}

declare module "@cerebral/http/lib/utils" {
  declare module.exports: any;
}

declare module "@cerebral/http/operators" {
  declare module.exports: any;
}

declare module "@cerebral/http/typescript/typescript.spec" {
  declare module.exports: any;
}

// Filename aliases
declare module "@cerebral/http/lib/DEFAULT_OPTIONS.js" {
  declare module.exports: $Exports<"@cerebral/http/lib/DEFAULT_OPTIONS">;
}
declare module "@cerebral/http/lib/fileUpload.js" {
  declare module.exports: $Exports<"@cerebral/http/lib/fileUpload">;
}
declare module "@cerebral/http/lib/HttpProviderError.js" {
  declare module.exports: $Exports<"@cerebral/http/lib/HttpProviderError">;
}
declare module "@cerebral/http/lib/index.js" {
  declare module.exports: $Exports<"@cerebral/http/lib/index">;
}
declare module "@cerebral/http/lib/operators/httpDelete.js" {
  declare module.exports: $Exports<"@cerebral/http/lib/operators/httpDelete">;
}
declare module "@cerebral/http/lib/operators/httpGet.js" {
  declare module.exports: $Exports<"@cerebral/http/lib/operators/httpGet">;
}
declare module "@cerebral/http/lib/operators/httpPatch.js" {
  declare module.exports: $Exports<"@cerebral/http/lib/operators/httpPatch">;
}
declare module "@cerebral/http/lib/operators/httpPost.js" {
  declare module.exports: $Exports<"@cerebral/http/lib/operators/httpPost">;
}
declare module "@cerebral/http/lib/operators/httpPut.js" {
  declare module.exports: $Exports<"@cerebral/http/lib/operators/httpPut">;
}
declare module "@cerebral/http/lib/operators/httpUploadFile.js" {
  declare module.exports: $Exports<
    "@cerebral/http/lib/operators/httpUploadFile"
  >;
}
declare module "@cerebral/http/lib/operators/index.js" {
  declare module.exports: $Exports<"@cerebral/http/lib/operators/index">;
}
declare module "@cerebral/http/lib/request.js" {
  declare module.exports: $Exports<"@cerebral/http/lib/request">;
}
declare module "@cerebral/http/lib/utils.js" {
  declare module.exports: $Exports<"@cerebral/http/lib/utils">;
}
declare module "@cerebral/http/operators.js" {
  declare module.exports: $Exports<"@cerebral/http/operators">;
}
declare module "@cerebral/http/typescript/typescript.spec.js" {
  declare module.exports: $Exports<"@cerebral/http/typescript/typescript.spec">;
}
