// flow-typed signature: d0fd2fdcbdfe85e76d6e735921b13ce8
// flow-typed version: <<STUB>>/@cerebral/router_v^0.0.0-beta.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@cerebral/router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@cerebral/router" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@cerebral/router/base" {
  declare module.exports: any;
}

declare module "@cerebral/router/lib/base" {
  declare module.exports: any;
}

declare module "@cerebral/router/lib/index" {
  declare module.exports: any;
}

declare module "@cerebral/router/lib/operators/goTo" {
  declare module.exports: any;
}

declare module "@cerebral/router/lib/operators/index" {
  declare module.exports: any;
}

declare module "@cerebral/router/lib/operators/redirect" {
  declare module.exports: any;
}

declare module "@cerebral/router/lib/operators/redirectToSignal" {
  declare module.exports: any;
}

declare module "@cerebral/router/lib/operators/reload" {
  declare module.exports: any;
}

declare module "@cerebral/router/lib/router" {
  declare module.exports: any;
}

declare module "@cerebral/router/lib/testSetup" {
  declare module.exports: any;
}

declare module "@cerebral/router/lib/utils" {
  declare module.exports: any;
}

declare module "@cerebral/router/operators" {
  declare module.exports: any;
}

// Filename aliases
declare module "@cerebral/router/base.js" {
  declare module.exports: $Exports<"@cerebral/router/base">;
}
declare module "@cerebral/router/lib/base.js" {
  declare module.exports: $Exports<"@cerebral/router/lib/base">;
}
declare module "@cerebral/router/lib/index.js" {
  declare module.exports: $Exports<"@cerebral/router/lib/index">;
}
declare module "@cerebral/router/lib/operators/goTo.js" {
  declare module.exports: $Exports<"@cerebral/router/lib/operators/goTo">;
}
declare module "@cerebral/router/lib/operators/index.js" {
  declare module.exports: $Exports<"@cerebral/router/lib/operators/index">;
}
declare module "@cerebral/router/lib/operators/redirect.js" {
  declare module.exports: $Exports<"@cerebral/router/lib/operators/redirect">;
}
declare module "@cerebral/router/lib/operators/redirectToSignal.js" {
  declare module.exports: $Exports<
    "@cerebral/router/lib/operators/redirectToSignal"
  >;
}
declare module "@cerebral/router/lib/operators/reload.js" {
  declare module.exports: $Exports<"@cerebral/router/lib/operators/reload">;
}
declare module "@cerebral/router/lib/router.js" {
  declare module.exports: $Exports<"@cerebral/router/lib/router">;
}
declare module "@cerebral/router/lib/testSetup.js" {
  declare module.exports: $Exports<"@cerebral/router/lib/testSetup">;
}
declare module "@cerebral/router/lib/utils.js" {
  declare module.exports: $Exports<"@cerebral/router/lib/utils">;
}
declare module "@cerebral/router/operators.js" {
  declare module.exports: $Exports<"@cerebral/router/operators">;
}
