// flow-typed signature: 6e3bb17d63105fd36971ad27e8508d5c
// flow-typed version: <<STUB>>/@cerebral/shortcuts_v^0.0.0-beta.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@cerebral/shortcuts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@cerebral/shortcuts" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@cerebral/shortcuts/lib/index" {
  declare module.exports: any;
}

declare module "@cerebral/shortcuts/lib/index.test" {
  declare module.exports: any;
}

// Filename aliases
declare module "@cerebral/shortcuts/lib/index.js" {
  declare module.exports: $Exports<"@cerebral/shortcuts/lib/index">;
}
declare module "@cerebral/shortcuts/lib/index.test.js" {
  declare module.exports: $Exports<"@cerebral/shortcuts/lib/index.test">;
}
