// flow-typed signature: 5a062784479e3832d6554d0741c73240
// flow-typed version: <<STUB>>/@cerebral/storage_v^0.0.0-beta.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@cerebral/storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@cerebral/storage" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@cerebral/storage/lib/index" {
  declare module.exports: any;
}

declare module "@cerebral/storage/lib/operators/getStorage" {
  declare module.exports: any;
}

declare module "@cerebral/storage/lib/operators/index" {
  declare module.exports: any;
}

declare module "@cerebral/storage/lib/operators/removeStorage" {
  declare module.exports: any;
}

declare module "@cerebral/storage/lib/operators/setStorage" {
  declare module.exports: any;
}

declare module "@cerebral/storage/operators" {
  declare module.exports: any;
}

declare module "@cerebral/storage/src/index" {
  declare module.exports: any;
}

declare module "@cerebral/storage/src/operators/getStorage" {
  declare module.exports: any;
}

declare module "@cerebral/storage/src/operators/index" {
  declare module.exports: any;
}

declare module "@cerebral/storage/src/operators/removeStorage" {
  declare module.exports: any;
}

declare module "@cerebral/storage/src/operators/setStorage" {
  declare module.exports: any;
}

// Filename aliases
declare module "@cerebral/storage/lib/index.js" {
  declare module.exports: $Exports<"@cerebral/storage/lib/index">;
}
declare module "@cerebral/storage/lib/operators/getStorage.js" {
  declare module.exports: $Exports<
    "@cerebral/storage/lib/operators/getStorage"
  >;
}
declare module "@cerebral/storage/lib/operators/index.js" {
  declare module.exports: $Exports<"@cerebral/storage/lib/operators/index">;
}
declare module "@cerebral/storage/lib/operators/removeStorage.js" {
  declare module.exports: $Exports<
    "@cerebral/storage/lib/operators/removeStorage"
  >;
}
declare module "@cerebral/storage/lib/operators/setStorage.js" {
  declare module.exports: $Exports<
    "@cerebral/storage/lib/operators/setStorage"
  >;
}
declare module "@cerebral/storage/operators.js" {
  declare module.exports: $Exports<"@cerebral/storage/operators">;
}
declare module "@cerebral/storage/src/index.js" {
  declare module.exports: $Exports<"@cerebral/storage/src/index">;
}
declare module "@cerebral/storage/src/operators/getStorage.js" {
  declare module.exports: $Exports<
    "@cerebral/storage/src/operators/getStorage"
  >;
}
declare module "@cerebral/storage/src/operators/index.js" {
  declare module.exports: $Exports<"@cerebral/storage/src/operators/index">;
}
declare module "@cerebral/storage/src/operators/removeStorage.js" {
  declare module.exports: $Exports<
    "@cerebral/storage/src/operators/removeStorage"
  >;
}
declare module "@cerebral/storage/src/operators/setStorage.js" {
  declare module.exports: $Exports<
    "@cerebral/storage/src/operators/setStorage"
  >;
}
