// flow-typed signature: 056203bfcb1b500c5c9c59aec7a87a51
// flow-typed version: <<STUB>>/@cerebral/useragent_v^0.0.0-beta.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@cerebral/useragent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@cerebral/useragent" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@cerebral/useragent/lib/getFeatures" {
  declare module.exports: any;
}

declare module "@cerebral/useragent/lib/getMedia" {
  declare module.exports: any;
}

declare module "@cerebral/useragent/lib/getWindowSpec" {
  declare module.exports: any;
}

declare module "@cerebral/useragent/lib/index" {
  declare module.exports: any;
}

declare module "@cerebral/useragent/lib/network" {
  declare module.exports: any;
}

declare module "@cerebral/useragent/lib/parseUserAgent" {
  declare module.exports: any;
}

declare module "@cerebral/useragent/lib/signalFactories/offlineChanged" {
  declare module.exports: any;
}

declare module "@cerebral/useragent/lib/signalFactories/windowChanged" {
  declare module.exports: any;
}

// Filename aliases
declare module "@cerebral/useragent/lib/getFeatures.js" {
  declare module.exports: $Exports<"@cerebral/useragent/lib/getFeatures">;
}
declare module "@cerebral/useragent/lib/getMedia.js" {
  declare module.exports: $Exports<"@cerebral/useragent/lib/getMedia">;
}
declare module "@cerebral/useragent/lib/getWindowSpec.js" {
  declare module.exports: $Exports<"@cerebral/useragent/lib/getWindowSpec">;
}
declare module "@cerebral/useragent/lib/index.js" {
  declare module.exports: $Exports<"@cerebral/useragent/lib/index">;
}
declare module "@cerebral/useragent/lib/network.js" {
  declare module.exports: $Exports<"@cerebral/useragent/lib/network">;
}
declare module "@cerebral/useragent/lib/parseUserAgent.js" {
  declare module.exports: $Exports<"@cerebral/useragent/lib/parseUserAgent">;
}
declare module "@cerebral/useragent/lib/signalFactories/offlineChanged.js" {
  declare module.exports: $Exports<
    "@cerebral/useragent/lib/signalFactories/offlineChanged"
  >;
}
declare module "@cerebral/useragent/lib/signalFactories/windowChanged.js" {
  declare module.exports: $Exports<
    "@cerebral/useragent/lib/signalFactories/windowChanged"
  >;
}
